'use strict';
const {TYPES}=require('./engine-v2.cjs');
// Explicit public whitelist. No RNG state, hidden valuations or private NPC parameters.
function trader(m,a){return {id:a.id,name:a.name,type:a.type,typeName:TYPES[a.type]||'玩家',cash:a.cash,shares:[...a.shares],cost:[...a.cost],skill:a.skill,lastIncome:a.lastIncome,totalIncome:a.totalIncome,realized:a.realized,debt:a.debt,financeCosts:a.financeCosts,leverageLimit:a.leverageLimit,liquidating:a.liquidating,initialEquity:a.initialEquity,equity:m.equity(a),investment:m.investment(a),action:a.action||'等待',analysis:a.analysis||'',analystStyle:a.analystStyle||'',knownSymbols:(a.knownSymbols||[]).map(i=>m.stocks[i].symbol)};}
function page(list,args={},fallback=100){const count=Number(args.count??fallback),offset=Number(args.offset??0);if(!Number.isInteger(count)||count<0||count>100000||!Number.isSafeInteger(offset)||offset<0)throw new Error('条数须为 0–100000，偏移须为非负整数。');return list.slice(offset,count===0?undefined:offset+count);}
function stock(m,i){const s=m.stocks[i];return {symbol:s.symbol,sector:s.sector,color:s.color,start:s.start,supply:s.supply,price:s.price,publicValue:s.publicValue,previous:s.previous,volatility:s.volatility,volume:s.volume,turnover:s.turnover,totalBars:s.candles.length+(s.pendingBar?1:0),indicators:m.indicators(i)};}
function own(m){const p=m.player;return {...trader(m,p),tick:m.tick,phase:m.phase,gross:m.gross(p),availableCash:m.availableCash(p.id),reservedCash:m.reservedCash(p.id),availableShares:p.shares.map((_,i)=>m.availableShares(p.id,i)),reservedShares:p.shares.map((_,i)=>m.reservedShares(p.id,i)),positions:m.stocks.map((s,i)=>({symbol:s.symbol,qty:p.shares[i],available:m.availableShares(p.id,i),reserved:m.reservedShares(p.id,i),cost:p.cost[i],price:s.price,value:p.shares[i]*s.price,unrealized:p.shares[i]*(s.price-p.cost[i])})),margin:m.margin()};}
function rules(m){return {currency:'USD',symbols:m.stocks.map(s=>s.symbol),cashRate:m.cashRate,loanRate:m.loanRate,skillIncome:m.player.skill,leverageLimits:Array.from({length:100},(_,i)=>i+1),maxLeverage:100,marginPolicy:{fixedThrough:3,fixedMaintenance:.25,fixedRecovery:.35,maintenanceNumerator:.75,recoveryNumerator:.9},matching:"parallel-per-stock-batches",maintenance:m.maintenance,recovery:m.recovery,shortSelling:false,transactionFee:0,newsInterval:18,reportInterval:36,reportLag:6,goalEquity:m.goalEquity,goalInvestment:m.goalInvestment,maxTraders:100000,wealthDistribution:{kind:"truncated-pareto",alpha:1.25,min:1200,max:1e7},speedOpportunities:2,maxCalls:2000,orderTTLMax:1000};}
function info(m){return {performance:{...m.performance},acceleration:m.acceleration,tick:m.tick,phase:m.phase,inTick:m.inTick,count:m.count,playerId:m.playerId,won:m.won||false,lastTrades:m.lastTrades,activity:{...m.activity},totalTrades:(m.tradeArchive||[]).length,totalPlayerTrades:m.playerTrades.length,totalEvents:(m.eventArchive||[]).length,types:TYPES,rules:rules(m)};}
function news(e){const match=/^([A-E]) 行业(利好|利空)$/.exec(e.title);return {...e,symbol:match?.[1]||'',direction:match?(match[2]==='利好'?1:-1):0};}
module.exports={trader,page,stock,own,rules,info,news};
