'use strict';
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
function init(m,volatility){m.economy={factor:1,volatility,history:[{tick:0,factor:1}]};m.companyHistory=[];for(const s of m.stocks){const c={cash:s.supply*s.start*.12,debt:s.supply*s.start*.06,productivity:1,demand:1,margin:.18,cashFlow:s.supply*s.start*(.00036-.06*m.loanRate),revenue:s.supply*s.start*.002,expenses:s.supply*s.start*.00164,window:[],lastDividend:0,lastDividendTick:0,totalDividends:0,dividendHistory:[],newsSentiment:0};s.company=c;c.report=report(m,s);}}
function report(m,s){const c=s.company;return {symbol:s.symbol,reportTick:m.tick,cash:c.cash,debt:c.debt,revenue:c.revenue,expenses:c.expenses,operatingMargin:c.margin,cashFlow:c.cashFlow,productivity:c.productivity,demand:c.demand,bookValuePerShare:(c.cash-c.debt)/s.supply,dividendPerShare:c.lastDividend,lastDividendTick:c.lastDividendTick,totalDividends:c.totalDividends};}
function publicCompany(m,s){return {...s.company.report,dividendPerShare:s.company.lastDividend,lastDividendTick:s.company.lastDividendTick,totalDividends:s.company.totalDividends,dividendHistory:s.company.dividendHistory.slice(-60)};}
function step(m){const e=m.economy;e.factor=clamp(e.factor*Math.exp(-.02*Math.log(e.factor)+e.volatility*(m.random()*2-1)),.1,5);e.history.push({tick:m.tick,factor:e.factor});
 for(const s of m.stocks){const c=s.company;c.productivity=clamp(c.productivity*Math.exp(-.015*Math.log(c.productivity)+(m.random()-.5)*s.volatility*.35),.3,3);c.demand=clamp(c.demand*Math.exp(-.025*Math.log(c.demand)+(m.random()-.5)*s.volatility*.6),.3,3);c.margin=clamp(c.margin+(.18-c.margin)*.025+(m.random()-.5)*.016,-.2,.5);c.newsSentiment*=.985;c.revenue=s.supply*s.start*.002*e.factor*c.productivity*c.demand;c.expenses=c.revenue*(1-c.margin);c.cashFlow=c.revenue-c.expenses-c.debt*m.loanRate;c.cash+=c.cashFlow;
 // Operating deficits become company debt; this is distinct from trader margin debt.
 if(c.cash<0){c.debt-=c.cash;c.cash=0;}c.window.push(c.cashFlow);if(c.window.length>12)c.window.shift();const flow=c.window.reduce((v,n)=>v+n,0)/c.window.length;
 if(m.tick%12===0&&flow>0&&c.margin>0){const payout=Math.min(Math.max(0,c.cash-s.supply*s.start*.06),flow*12*.35),perShare=Math.floor(payout/s.supply*10000)/10000;if(perShare>0){const paid=perShare*s.supply;c.cash-=paid;c.totalDividends+=paid;c.lastDividend=perShare;c.lastDividendTick=m.tick;c.dividendHistory.push({tick:m.tick,perShare,amount:paid});m.minted+=paid;for(const a of m.people){const amount=(a.shares[s.index]+a.lent[s.index]-a.shorts[s.index])*perShare;if(!amount)continue;const d=m.changeCash(a,amount);a.totalDividends+=amount;if(a.id===m.playerId)m.recordAccount('dividend',amount,d.cashDelta,d.debtDelta,{symbol:s.symbol,perShare,held:a.shares[s.index],lent:a.lent[s.index],short:a.shorts[s.index]});}m.event(`${s.symbol} 公司分红`,`经营现金流支持每股 $${perShare.toFixed(4)} 分红；空头承担补偿，不保证每期分红。`);}}
 s.fair=clamp((s.start*.5+(c.cash-c.debt)/s.supply+clamp(flow/s.supply*250,-s.start*.4,s.start*4))/.6425*Math.exp(c.newsSentiment),.01,1e7);
 if(m.tick%12===0){c.report=report(m,s);m.companyHistory.push({...c.report});}}
 if(m.tick%12===0)m.event('公司财报公布','五家公司公开本期经营现金流、现金、债务和利润率，内幕交易者此前可读取最新内部经营信息。');}
module.exports={init,step,publicCompany};
