'use strict';
const TYPES=['价值投资','趋势追踪','逆向交易','流动性做市','短线投机','内幕交易','速度派量化','分析派量化'];
const round=v=>Math.round(v*100)/100,clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
class Market {
 constructor(seed=Date.now(),count=1000){
  if(typeof seed==='object'){count=seed.count??1000;seed=seed.seed??Date.now();}
  if(!Number.isInteger(count)||count<50||count>5000)throw new Error('交易者人数须为 50–5000 的整数。');
  this.seed=Number(seed)>>>0;this.tick=0;this.count=count;this.playerId=count;this.orderId=0;this.orders=[];this.trades=[];this.playerTrades=[];this.events=[];this.minted=0;this.bankCash=0;this.cashRate=.0001;this.loanRate=.0005;this.maintenance=.25;this.recovery=.35;this.checkingMargin=false;this.inTick=false;this.phase='manual';this.lastTrades=0;this.activity={buy:0,sell:0,wait:0};this.actionSequence=[];
  this.stocks=[['A','科技',100,'#7d9cff',.022],['B','能源',65,'#f3ba63',.034],['C','消费',42,'#c19aff',.015],['D','医药',125,'#67d6bd',.029],['E','工业',80,'#f28ca6',.02]].map(([symbol,sector,price,color,volatility])=>({symbol,sector,price,color,start:price,fair:price,publicValue:price,fairHistory:[price],previous:price,volatility,candles:[],history:[],volume:0,turnover:0}));
  const insider=Math.max(1,Math.floor(count*.03)),speed=Math.max(1,Math.floor(count*.02)),analyst=Math.max(1,Math.floor(count*.03)),ordinary=count-insider-speed-analyst;
  this.agents=Array.from({length:count},(_,id)=>{const type=id<ordinary?id%5:id<ordinary+insider?5:id<ordinary+insider+speed?6:7;const focus=Math.floor(this.random()*5),known=[focus];if(type===5){while(known.length<1+id%3){const i=Math.floor(this.random()*5);if(!known.includes(i))known.push(i);}}
   return {id,name:`交易者 ${String(id+1).padStart(4,'0')}`,type,cash:round(3000+this.random()*14000),shares:this.stocks.map(()=>Math.floor(20+this.random()*61)),cost:[0,0,0,0,0],skill:round(.5+this.random()*7.5),risk:.15+this.random()*.8,bias:this.random()*2-1,valuationBias:(this.random()-.5)*.025,focus,knownSymbols:type===5?known:[],lastIncome:0,action:'等待',totalIncome:0,realized:0,debt:0,financeCosts:0,leverageLimit:1,liquidating:false};});
  this.player={id:count,name:'你',type:-1,cash:10000,shares:[0,0,0,0,0],cost:[0,0,0,0,0],skill:3,lastIncome:0,totalIncome:0,realized:0,debt:0,financeCosts:0,leverageLimit:1,liquidating:false};this.people=[...this.agents,this.player];
  this.people.forEach(a=>{a.initialEquity=this.equity(a);a.cost=a.shares.map((_,i)=>this.stocks[i].start);});this.player.cost.fill(0);this.initialCash=this.people.reduce((s,a)=>s+a.cash,0);this.equityHistory=[10000];
  this.stocks.forEach(s=>s.candles.push(this.emptyBar(s,0)));this.stocks.forEach(s=>s.history=[s.price]);
  // Opening liquidity is two-sided and passive; the reference price is not moved by a fabricated opening trade.
  this.initializing=true;this.agents.filter(a=>a.type===3).forEach(a=>{for(let i=0;i<5;i++)this.makeMarket(a,i);});this.initializing=false;
  this.event('市场开盘',`${count} 位交易者入场：内幕 ${insider}、速度量化 ${speed}、分析量化 ${analyst}。普通交易者不读取内部估值。`);
 }
 random(){let t=this.seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;}
 shuffle(a){const r=[...a];for(let i=r.length-1;i>0;i--){const j=Math.floor(this.random()*(i+1));[r[i],r[j]]=[r[j],r[i]];}return r;}
 event(title,body){this.eventArchive??=[];const e={id:this.eventArchive.length+1,tick:this.tick,title,body};this.eventArchive.push(e);this.events.unshift(e);this.events=this.events.slice(0,100);}
 emptyBar(s,tick){return {tick,open:s.price,high:s.price,low:s.price,close:s.price,volume:0,turnover:0,trades:0,vwap:s.price,complete:tick===0};}
 currentBar(i){const s=this.stocks[i];if(this.inTick||this.initializing)return s.candles.at(-1);if(!s.pendingBar){s.pendingBar=this.emptyBar(s,this.tick+1);s.pendingBar.open=s.candles.at(-1).close;s.pendingBar.high=Math.max(s.pendingBar.open,s.price);s.pendingBar.low=Math.min(s.pendingBar.open,s.price);s.volume=0;s.turnover=0;}return s.pendingBar;}
 gross(a){return a.cash+a.shares.reduce((s,q,i)=>s+q*this.stocks[i].price,0);}
 equity(a){return this.gross(a)-a.debt;}
 investment(a){return this.equity(a)-a.initialEquity-a.totalIncome;}
 recordAccount(type,amount,cashDelta,debtDelta,details={}){this.accountLedger??=[];const p=this.player;this.accountLedger.push({id:this.accountLedger.length+1,tick:this.tick,phase:this.phase,type,amount,cashDelta,debtDelta,cash:p.cash,debt:p.debt,equity:this.equity(p),realized:p.realized,details});}
 ranking(mode='equity'){const rows=this.people.map(a=>({id:a.id,name:a.name,type:a.type,equity:this.equity(a),debt:a.debt,returnPct:(this.equity(a)/a.initialEquity-1)*100,tradingReturnPct:this.investment(a)/a.initialEquity*100}));const key=mode==='return'?'returnPct':mode==='trading'?'tradingReturnPct':'equity';return rows.sort((a,b)=>b[key]-a[key]||a.id-b.id).map((r,i)=>({...r,rank:i+1}));}
 margin(){const p=this.player,gross=this.gross(p),equity=this.equity(p);return {debt:p.debt,gross,equity,limit:p.leverageLimit,ratio:gross>0?equity/gross:1,leverage:equity>0?gross/equity:null,capacity:p.liquidating?0:Math.max(0,(p.leverageLimit-1)*equity-p.debt),interest:p.debt*this.loanRate,liquidating:p.liquidating};}
 setLeverage(v){if(![1,2,3].includes(v))return {ok:false,message:'融资上限须为 1、2、3 倍。'};if(this.player.debt>(v-1)*Math.max(0,this.equity(this.player))+1e-7)return {ok:false,message:'先还款，再降低融资上限。'};this.player.leverageLimit=v;return {ok:true,message:`融资上限已设为 ${v}×。`};}
 borrow(amount){if(!Number.isFinite(amount)||amount<.01)return {ok:false,message:'借款金额至少 $0.01。'};amount=round(amount);const m=this.margin();if(m.liquidating||m.equity<=0||amount>m.capacity+1e-7)return {ok:false,message:'超过可借额度，或账户正在强平。'};this.player.cash+=amount;this.player.debt+=amount;this.bankCash-=amount;this.recordAccount('borrow',amount,amount,amount);return {ok:true,amount,message:`已借入 $${amount.toFixed(2)}，净资产不变。`};}
 repay(amount){if(!Number.isFinite(amount)||amount<.01)return {ok:false,message:'还款金额至少 $0.01。'};const p=this.player,paid=Math.min(round(amount),p.debt,this.availableCash(p.id));if(paid<1e-7)return {ok:false,message:'没有可用现金或没有负债。'};p.cash-=paid;p.debt-=paid;this.bankCash+=paid;if(p.debt<1e-7)p.debt=0;if(!p.debt||this.margin().ratio>=this.recovery)p.liquidating=false;this.recordAccount('repay',paid,-paid,-paid);return {ok:true,amount:paid,message:`已还款 $${paid.toFixed(2)}。`};}
 reservedCash(id){return this.orders.reduce((s,o)=>s+(o.owner===id&&o.side==='buy'?o.qty*o.price:0),0);}
 reservedShares(id,i){return this.orders.reduce((s,o)=>s+(o.owner===id&&o.stock===i&&o.side==='sell'?o.qty:0),0);}
 availableCash(id){return Math.max(0,this.people[id].cash-this.reservedCash(id));}
 availableShares(id,i){return Math.max(0,this.people[id].shares[i]-this.reservedShares(id,i));}
 cancel(id,owner=this.playerId){const idx=this.orders.findIndex(o=>o.id===id&&o.owner===owner);if(idx<0)return false;this.orders.splice(idx,1);return true;}
 cancelAll(owner=this.playerId){const before=this.orders.length;this.orders=this.orders.filter(o=>o.owner!==owner);return before-this.orders.length;}
 book(i){return {buy:this.orders.filter(o=>o.stock===i&&o.side==='buy').sort((a,b)=>b.price-a.price||a.id-b.id),sell:this.orders.filter(o=>o.stock===i&&o.side==='sell').sort((a,b)=>a.price-b.price||a.id-b.id)};}
 execute(buy,sell,price){const i=buy.stock,qty=Math.min(buy.qty,sell.qty),amount=qty*price,b=this.people[buy.owner],s=this.people[sell.owner],stock=this.stocks[i];const old=b.shares[i];b.cost[i]=(b.cost[i]*old+amount)/(old+qty);s.realized+=qty*(price-s.cost[i]);b.cash-=amount;s.cash+=amount;b.shares[i]+=qty;s.shares[i]-=qty;buy.qty-=qty;sell.qty-=qty;if(!s.shares[i])s.cost[i]=0;
  const bar=this.currentBar(i);stock.price=price;stock.volume+=qty;stock.turnover+=amount;this.lastTrades++;bar.high=Math.max(bar.high,price);bar.low=Math.min(bar.low,price);bar.close=price;bar.volume+=qty;bar.turnover+=amount;bar.trades++;bar.vwap=bar.turnover/bar.volume;
  // Only the mutable current candle changes; prior candles are never rewritten.
  if(this.inTick||this.initializing)stock.history[stock.history.length-1]=price;this.tradeArchive??=[];const t={id:this.tradeArchive.length+1,tick:bar.tick,stock:i,price,qty,buyer:b.id,seller:s.id,phase:this.phase};this.tradeArchive.push(t);this.trades.unshift(t);if(this.trades.length>1000)this.trades.length=1000;if(b.id===this.playerId||s.id===this.playerId){this.playerTrades.unshift(t);this.recordAccount(b.id===this.playerId?'buy':'sell',amount,b.id===this.playerId?-amount:amount,0,{tradeId:t.id,symbol:stock.symbol,qty,price,buyer:b.id,seller:s.id,candleTick:bar.tick});}
 }
 matchIncoming(order){const opposite=this.book(order.stock)[order.side==='buy'?'sell':'buy'];for(const resting of opposite){if(!order.qty)break;if(!resting.qty||resting.owner===order.owner||resting.id===order.id)continue;if(order.side==='buy'?resting.price>order.price:resting.price<order.price)break;this.execute(order.side==='buy'?order:resting,order.side==='sell'?order:resting,resting.price);}this.orders=this.orders.filter(o=>o.qty>0);}
 place(id,i,side,qty,price,ttl=8,kind='limit'){
  if(!Number.isInteger(id)||!this.people[id]||!Number.isInteger(i)||!this.stocks[i]||!['buy','sell'].includes(side)||!Number.isSafeInteger(qty)||qty<1||!Number.isFinite(price)||price<.01||price>1e7||!Number.isInteger(ttl)||ttl<1||ttl>1000)return {ok:false,message:'交易参数无效：整股、正价格、有效期 1–1000 刻。'};
  price=round(price);if(id===this.playerId&&side==='buy'&&this.player.liquidating)return {ok:false,message:'强平中不能买入。'};if(side==='buy'&&qty*price>this.availableCash(id)+1e-7)return {ok:false,message:'可用现金不足。'};if(side==='sell'&&qty>this.availableShares(id,i))return {ok:false,message:'可卖持仓不足。'};
  const order={id:++this.orderId,owner:id,stock:i,side,qty,original:qty,price,tick:this.tick,expires:this.tick+ttl,kind};this.orders.push(order);this.matchIncoming(order);return {ok:true,order,filled:qty-order.qty};
 }
 trade(id,i,side,qty,kind='market',price=0,ttl=30){
  if(!this.people[id]||!Number.isInteger(i)||!this.stocks[i]||!['buy','sell'].includes(side)||!Number.isSafeInteger(qty)||qty<1||!['market','limit'].includes(kind))return {ok:false,message:'无效交易参数。'};
  if(id===this.playerId&&side==='buy'&&this.player.liquidating)return {ok:false,message:'强平中不能买入。'};
  let result;
  if(kind==='limit'){result=this.place(id,i,side,qty,Number(price),ttl,kind);if(!result.ok)return result;}
  else{const opposite=this.book(i)[side==='buy'?'sell':'buy'];let remaining=qty,total=0,limit=0;for(const o of opposite){if(o.owner===id)continue;const q=Math.min(remaining,o.qty);total+=q*o.price;limit=o.price;remaining-=q;if(!remaining)break;}const fill=qty-remaining;if(!fill)return {ok:false,message:'没有其他交易者的对手盘。'};if(side==='buy'&&total>this.availableCash(id)+1e-7)return {ok:false,message:'可用美元不足，请减少数量。'};if(side==='sell'&&qty>this.availableShares(id,i))return {ok:false,message:'可卖持仓不足。'};
   const order={id:++this.orderId,owner:id,stock:i,side,qty:fill,original:fill,price:limit,tick:this.tick,expires:this.tick+1,kind};this.orders.push(order);this.matchIncoming(order);this.cancel(order.id,id);result={ok:true,order,filled:fill-order.qty};}
  if(id===this.playerId&&!this.checkingMargin)this.checkMargin();this.equityHistory[this.tick]=this.equity(this.player);return {ok:true,filled:result.filled,orderId:result.order.qty&&kind==='limit'?result.order.id:null,remaining:kind==='limit'?result.order.qty:qty-result.filled,message:`${side==='buy'?'买入':'卖出'} ${this.stocks[i].symbol}：成交 ${result.filled} 股${kind==='limit'&&result.order.qty?'，剩余挂单 '+result.order.qty+' 股':''}。`};
 }
 submit(i,side,qty,kind,price,ttl=30){return this.trade(this.playerId,i,side,qty,kind,price,ttl);}
 checkMargin(){
  if(this.checkingMargin)return;const p=this.player,m=this.margin();if(!m.debt||(!m.liquidating&&m.equity>0&&m.ratio>=this.maintenance))return;
  this.checkingMargin=true;const oldPhase=this.phase;this.phase='liquidation';
  try{if(!p.liquidating)this.event('保证金不足，开始减仓','比例低于 25%。撤单并通过真实对手盘减仓还款，恢复到 35% 后停止。');p.liquidating=true;this.cancelAll();if(this.availableCash(p.id)>.000001)this.repay(Math.max(.01,this.availableCash(p.id)));
   // Sell only what the next actual bid needs to restore the recovery ratio; stop without liquidating the full portfolio.
   let attempts=0;while(p.debt>1e-7&&this.margin().ratio<this.recovery&&attempts++<10000){let candidate=null;for(let i=0;i<5;i++){if(!this.availableShares(p.id,i))continue;const bid=this.book(i).buy.find(o=>o.owner!==p.id);if(bid&&(!candidate||bid.qty*bid.price>candidate.bid.qty*candidate.bid.price))candidate={i,bid};}if(!candidate)break;
    const {i,bid}=candidate,now=this.margin(),mark=this.stocks[i].price,postEquity=now.equity+p.shares[i]*(bid.price-mark),postGross=now.gross+p.shares[i]*(bid.price-mark);let needed=postEquity>0?Math.ceil((postGross-postEquity/this.recovery)/bid.price):this.availableShares(p.id,i);const q=Math.max(1,Math.min(this.availableShares(p.id,i),bid.qty,needed,Math.ceil(p.debt/bid.price)));
    const r=this.trade(p.id,i,'sell',q,'market');if(!r.ok||!r.filled)break;if(this.availableCash(p.id)>.000001)this.repay(Math.max(.01,this.availableCash(p.id)));}
   if(!p.debt||this.margin().ratio>=this.recovery){p.liquidating=false;this.event('保证金恢复','已恢复安全比例，停止强平；剩余持仓和负债保留。');}
  }finally{this.phase=oldPhase;this.checkingMargin=false;}
 }
 reference(i){const s=this.stocks[i],completed=s.candles.slice(-6).filter(b=>b.complete).slice(-5);const sum=completed.reduce((a,b)=>a+b.turnover,0),volume=completed.reduce((a,b)=>a+b.volume,0);return volume?sum/volume:completed.at(-1)?.close??s.start;}
 indicators(i,withBook=true){const s=this.stocks[i],cacheKey=`${this.tick}:${this.inTick}`;if(s.technicalCache?.key===cacheKey){const result={...s.technicalCache.value};if(withBook)result.imbalance=this.imbalance(i);return result;}const bars=s.candles.slice(-61).filter(b=>b.complete),h=bars.slice(-60).map(b=>b.close),p=h.at(-1)||s.price;const sma=n=>h.slice(-n).reduce((a,b)=>a+b,0)/Math.min(n,h.length);let ema=p;if(h.length){ema=h[0];for(const v of h)ema+=2/13*(v-ema);}const returns=h.slice(1).map((v,k)=>Math.log(v/h[k])),mean=returns.length?returns.reduce((a,b)=>a+b,0)/returns.length:0,vol=returns.length?Math.sqrt(returns.reduce((a,b)=>a+(b-mean)**2,0)/returns.length):0;
  let up=0,down=0;for(let k=Math.max(1,h.length-14);k<h.length;k++){const d=h[k]-h[k-1];up+=Math.max(0,d);down+=Math.max(0,-d);}const rsi=up+down?100*up/(up+down):50;
  const recent=h.slice(-24).map(Math.log),n=recent.length,mx=(n-1)/2,my=n?recent.reduce((a,b)=>a+b,0)/n:0;let cov=0,vx=0,vy=0;recent.forEach((v,k)=>{cov+=(k-mx)*(v-my);vx+=(k-mx)**2;vy+=(v-my)**2;});const slope=vx?cov/vx:0,r2=vx&&vy?cov*cov/(vx*vy):0;
  const mu=sma(20),sd=Math.sqrt(h.slice(-20).reduce((a,b)=>a+(b-mu)**2,0)/Math.min(20,h.length));const result={sma5:sma(5),sma20:mu,ema12:ema,rsi14:rsi,volatility:vol,regressionSlope:slope,regressionR2:r2,bollingerUpper:mu+2*sd,bollingerLower:mu-2*sd,zScore:sd?(p-mu)/sd:0,imbalance:0,momentum:h.length>5?p/h[h.length-6]-1:0};s.technicalCache={key:cacheKey,value:result};return {...result,imbalance:withBook?this.imbalance(i):0};
 }
 imbalance(i){const book=this.book(i),bq=book.buy.slice(0,10).reduce((a,b)=>a+b.qty,0),sq=book.sell.slice(0,10).reduce((a,b)=>a+b.qty,0);return bq+sq?(bq-sq)/(bq+sq):0;}
 makeMarket(a,i){const ref=this.reference(i),weight=a.shares[i]*ref/Math.max(1,this.equity(a)),shift=clamp((.13-weight)*.02,-.004,.004),center=ref*(1+shift),spread=.0025+this.stocks[i].volatility*.06,qty=2+Math.floor(this.random()*9);const bp=round(Math.max(.01,center*(1-spread))),sp=round(center*(1+spread));let n=0;const b=Math.min(qty,Math.floor(this.availableCash(a.id)/bp)),q=Math.min(qty,this.availableShares(a.id,i));if(b>0){this.place(a.id,i,'buy',b,bp,3);n++;}if(q>0){this.place(a.id,i,'sell',q,Math.max(bp+.01,sp),3);n++;}a.action=`做市 ${this.stocks[i].symbol} · 双边 ${n} 单`;return n;}
 decide(a){this.actionSequence.push({id:a.id,phase:this.phase});if(this.random()>.78){a.action='等待';this.activity.wait++;return;}const i=a.type===5?a.knownSymbols[Math.floor(this.random()*a.knownSymbols.length)]:this.random()<.6?a.focus:Math.floor(this.random()*5),s=this.stocks[i],ref=this.reference(i);
  if(a.type===3){this.cancelAll(a.id);if(this.makeMarket(a,i)){this.activity.buy++;this.activity.sell++;}else this.activity.wait++;return;}
  const ind=this.indicators(i,a.type===6||a.type===7),noise=(this.random()-.5)*s.volatility*(.35+a.risk),publicTarget=s.publicValue*Math.exp(a.valuationBias);let target=ref;
  if(a.type===0)target=publicTarget*Math.exp(noise*.35);if(a.type===1)target=ref*Math.exp(ind.momentum*.65+noise*.4);if(a.type===2)target=ref*Math.exp(-ind.momentum*.55+noise*.4);if(a.type===4)target=ref*Math.exp(noise+a.bias*.003);if(a.type===5)target=s.fair*Math.exp(noise*.08);
  if(a.type===6){this.cancelAll(a.id);target=ref*Math.exp(clamp(ind.imbalance*.004+ind.momentum*.25,-.025,.025));}
  if(a.type===7){const trend=ind.regressionR2>.4&&Math.abs(ind.regressionSlope)>.00015;const signal=trend?ind.regressionSlope*5+Math.log(ind.ema12/ref)*.4:-ind.zScore*.002+(50-ind.rsi14)*.00008;target=ref*Math.exp(clamp(signal,-.035,.035));a.analysis=trend?'回归趋势 + EMA':'布林回归 + RSI';}
  const signal=Math.log(target/ref),eq=Math.max(1,this.equity(a)),desired=eq*(.5+a.risk*.3)/5,inventory=(desired-a.shares[i]*ref)/Math.max(1,desired);const prob=clamp(.5+signal*(a.type===5?8:5)+inventory*.12,.08,.92),side=this.random()<prob?'buy':'sell';
  const spread=.001+this.random()*.002,price=round(Math.max(.01,target*(1+(side==='buy'?-1:1)*spread)));let qty=2+Math.floor(this.random()*11);if(a.type===5)qty=Math.ceil(qty*1.8);if(a.type===7)qty=Math.max(1,Math.floor(qty*clamp(.003/Math.max(.001,ind.volatility),.4,1.6)));
  qty=side==='buy'?Math.min(qty,Math.floor(this.availableCash(a.id)/price)):Math.min(qty,this.availableShares(a.id,i));if(!qty){a.action='等待';this.activity.wait++;return;}const r=this.place(a.id,i,side,qty,price,a.type===6?1:2+Math.floor(this.random()*7));a.action=r.ok?`${side==='buy'?'买':'卖'} ${s.symbol} ${qty} 股${r.filled?' · 成交 '+r.filled:''}`:'等待';this.activity[r.ok?side:'wait']++;
 }
 beginTick(){if(this.inTick)throw new Error('上一回合尚未结束。');this.tick++;this.inTick=true;this.phase='opening';this.lastTrades=0;this.activity={buy:0,sell:0,wait:0};this.actionSequence=[];
  this.stocks.forEach(s=>{s.previous=s.candles.at(-1).close;const bar=s.pendingBar||this.emptyBar(s,this.tick);s.pendingBar=null;s.volume=bar.volume;s.turnover=bar.turnover;this.lastTrades+=bar.trades;s.candles.push(bar);s.history.push(s.price);});this.orders=this.orders.filter(o=>o.expires>this.tick);
  this.people.forEach(a=>{const cashInterest=a.cash*this.cashRate,income=cashInterest+a.skill;a.cash+=income;a.lastIncome=income;a.totalIncome+=income;this.minted+=income;if(a.id===this.playerId)this.recordAccount('income',income,income,0,{cashInterest,skillIncome:a.skill});});const interest=this.player.debt*this.loanRate;this.player.debt+=interest;this.player.financeCosts+=interest;if(interest)this.recordAccount('loan_interest',interest,0,interest);this.checkMargin();
  this.stocks.forEach(s=>{s.fair=Math.max(1,s.fair*Math.exp((this.random()-.5)*.002));});
  if(this.tick%18===0){const i=Math.floor(this.random()*5),s=this.stocks[i],sign=this.random()<.5?-1:1,shock=.025+this.random()*.045;s.fair*=Math.exp(sign*shock);s.publicValue*=Math.exp(sign*shock*.35);this.event(`${s.symbol} 行业${sign>0?'利好':'利空'}`,`公开消息只反映方向和部分幅度；精确内部估值仅向掌握 ${s.symbol} 的内幕交易者开放。`);}
  this.stocks.forEach(s=>{s.fairHistory.push(s.fair);if(this.tick%36===0)s.publicValue=s.fairHistory[Math.max(0,this.tick-6)]*Math.exp((this.random()-.5)*.01);});
  if(this.tick%36===0)this.event('估值报告公布','公开估值根据六刻前的基本面更新，普通交易者可读取，内幕信息仍有时间优势。');
  this.phase='speed';this.shuffle(this.agents.filter(a=>a.type===6)).forEach(a=>this.decide(a));this.phase='player-bot';
 }
 finishTick(){if(!this.inTick)throw new Error('没有待完成回合。');this.phase='normal';this.shuffle(this.agents.filter(a=>a.type!==6)).forEach(a=>this.decide(a));this.checkMargin();this.stocks.forEach(s=>{const b=s.candles.at(-1);b.complete=true;b.close=s.price;b.vwap=b.volume?b.turnover/b.volume:b.close;});this.equityHistory[this.tick]=this.equity(this.player);this.inTick=false;this.phase='manual';
  if(!this.won&&this.equity(this.player)>=20000&&this.investment(this.player)>=10000){this.won=true;this.event('投资目标达成','扣除被动收入后的投资盈利达到 $10,000，且净资产达到 $20,000。');}
 }
 step(){this.beginTick();this.finishTick();}
 candles(i,timeframe=1,count=240,offset=0){if(!Number.isInteger(timeframe)||timeframe<1||timeframe>1000)throw new Error('周期须为 1–1000 刻。');const stock=this.stocks[i],src=stock.pendingBar?[...stock.candles,stock.pendingBar]:stock.candles,result=[];for(const b of src){const bucket=Math.floor(b.tick/timeframe);let r=result.at(-1);if(!r||r.bucket!==bucket){r={bucket,tick:b.tick,endTick:b.tick,open:b.open,high:b.high,low:b.low,close:b.close,volume:0,turnover:0,trades:0,complete:true};result.push(r);}r.endTick=b.tick;r.high=Math.max(r.high,b.high);r.low=Math.min(r.low,b.low);r.close=b.close;r.volume+=b.volume;r.turnover+=b.turnover;r.trades+=b.trades;r.complete=b.complete&&b.tick%timeframe===timeframe-1;}result.forEach(b=>b.vwap=b.volume?b.turnover/b.volume:b.close);const end=Math.max(0,result.length-offset);return count===0?result.slice(0,end):result.slice(Math.max(0,end-count),end);}
 snapshot(){return {tick:this.tick,count:this.count,playerId:this.playerId,inTick:this.inTick,phase:this.phase,initialCash:this.initialCash,minted:this.minted,cashRate:this.cashRate,loanRate:this.loanRate,maintenance:this.maintenance,recovery:this.recovery,lastTrades:this.lastTrades,activity:this.activity,won:!!this.won,
  player:structuredClone(this.player),people:this.people.map(a=>({...a,knownSymbols:a.knownSymbols?.map(i=>this.stocks[i].symbol)})),stocks:this.stocks.map(s=>({symbol:s.symbol,sector:s.sector,price:s.price,color:s.color,start:s.start,publicValue:s.publicValue,previous:s.previous,volatility:s.volatility,volume:s.volume,turnover:s.turnover,history:(s.pendingBar?[...s.history,s.pendingBar.close]:s.history).slice(-240),candles:(s.pendingBar?[...s.candles,s.pendingBar]:s.candles).slice(-240),totalBars:s.candles.length+(s.pendingBar?1:0)})),orders:this.orders,trades:this.trades.slice(0,80),playerTrades:this.playerTrades.slice(0,200),events:this.events.slice(0,24),margin:this.margin()};}
 summary(){return {tick:this.tick,cash:round(this.player.cash),availableCash:round(this.availableCash(this.playerId)),equity:round(this.equity(this.player)),debt:round(this.player.debt),investment:round(this.investment(this.player)),margin:this.margin(),shares:[...this.player.shares],stocks:this.stocks.map(s=>({symbol:s.symbol,price:s.price,publicValue:s.publicValue})),orders:this.orders.filter(o=>o.owner===this.playerId)};}
}
module.exports={Market,TYPES};
