'use strict';
const {OrderIndex}=require('./order-index.cjs');
const {SecuritiesLending}=require('./securities-lending.cjs'),economics=require('./economy.cjs');
const {cpuRisk}=require('./risk-model.cjs');
const matching=require('./parallel-match.cjs'),{policy}=require('./npc-finance.cjs');
const {STYLES:ANALYST_STYLES,forecast}=require('./analyst-model.cjs');
const analystTrader=require('./analyst-trader.cjs');
const TYPES=['价值投资','趋势追踪','逆向交易','流动性做市','短线投机','内幕交易','速度派量化','分析派量化'];
const round=v=>Math.round(v*100)/100,clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
class Market {
 constructor(seed=Date.now(),count=1000){
  const opts=typeof seed==='object'?seed:{};if(typeof seed==='object'){count=opts.count??1000;seed=opts.seed??Date.now();}
  const cashRate=opts.cashRate??.0001,loanRate=opts.loanRate??.0005,playerCash=opts.playerCash??10000,economyVolatility=opts.economyVolatility??.01;
  if(!Number.isFinite(cashRate)||cashRate<-.5||cashRate>.5||!Number.isFinite(loanRate)||loanRate<-.5||loanRate>.5)throw new Error('现金与债务利率须为 −50%～+50% / 刻。');
  if(!Number.isFinite(economyVolatility)||economyVolatility<0||economyVolatility>.5)throw new Error('经济波动幅度须为 0–50% / 刻。');
  if(!Number.isFinite(playerCash)||playerCash<100||playerCash>1e9)throw new Error('玩家初始资金须为 $100–$1,000,000,000。');
  this.acceleration=opts.acceleration??'auto';if(!['auto','gpu','cpu'].includes(this.acceleration))throw new Error('计算模式无效。');this.performance={backend:'CPU',device:'CPU',riskMs:0,tickMs:0};this.goalEquity=playerCash*2;this.goalInvestment=playerCash;
  if(!Number.isInteger(count)||count<50||count>100000)throw new Error('交易者人数须为 50–100000 的整数。');
  this.seed=Number(seed)>>>0;this.tick=0;this.count=count;this.playerId=count;this.orderId=0;this.orders=[];this.trades=[];this.playerTrades=[];this.events=[];this.minted=0;this.bankCash=0;this.cashRate=cashRate;this.loanRate=loanRate;this.maintenance=.25;this.recovery=.35;this.checkingMargin=false;this.inTick=false;this.phase='manual';this.lastTrades=0;this.activity={buy:0,sell:0,wait:0};this.actionSequence=[];
  this.stocks=[['A','科技',100,'#7d9cff',.022],['B','能源',65,'#f3ba63',.034],['C','消费',42,'#c19aff',.015],['D','医药',125,'#67d6bd',.029],['E','工业',80,'#f28ca6',.02]].map(([symbol,sector,price,color,volatility])=>({symbol,sector,price,color,start:price,fair:price,publicValue:price,fairHistory:[price],previous:price,volatility,candles:[],history:[],volume:0,turnover:0}));
  const insider=Math.max(1,Math.floor(count*.03)),speed=Math.max(1,Math.floor(count*.02)),analyst=Math.max(1,Math.floor(count*.03)),ordinary=count-insider-speed-analyst;
  this.agents=Array.from({length:count},(_,id)=>{const type=id<ordinary?id%5:id<ordinary+insider?5:id<ordinary+insider+speed?6:7;const focus=Math.floor(this.random()*5),known=[focus];if(type===5){while(known.length<1+id%3){const i=Math.floor(this.random()*5);if(!known.includes(i))known.push(i);}}
   // Truncated Pareto wealth: alpha 1.25, $1,200 minimum, $10m cap.
   const wealth=Math.min(1e7,1200/Math.pow(Math.max(1e-9,1-this.random()),1/1.25)),cashFraction=.35+this.random()*.3,cash=round(wealth*cashFraction),shares=this.stocks.map(stock=>Math.floor(wealth*(1-cashFraction)/5/stock.start));
   const loanProbability=type===5?.8:type===7?.65:type===6?.5:type===3?.08:.08+type*.035,usesLoans=this.random()<loanProbability;
   return {analystStyle:type===7?ANALYST_STYLES[(id-ordinary-insider-speed)%ANALYST_STYLES.length]:undefined,id,name:`交易者 ${String(id+1).padStart(4,'0')}`,type,cash,shares,cost:[0,0,0,0,0],skill:round(.5+this.random()*7.5),risk:.15+this.random()*.8,bias:this.random()*2-1,valuationBias:(this.random()-.5)*.025,focus,knownSymbols:type===5?known:[],lastIncome:0,action:'等待',totalIncome:0,realized:0,debt:0,financeCosts:0,leverageLimit:usesLoans?(this.random()<.4?3:2):1,usesLoans,loanPreference:.25+this.random()*.7,liquidating:false};});
  this.player={id:count,name:'你',type:-1,cash:round(playerCash),shares:[0,0,0,0,0],cost:[0,0,0,0,0],skill:3,lastIncome:0,totalIncome:0,realized:0,debt:0,financeCosts:0,leverageLimit:1,liquidating:false};this.people=[...this.agents,this.player];
  this.stocks.forEach((stock,i)=>stock.supply=this.agents.reduce((sum,a)=>sum+a.shares[i],0));this.people.forEach(a=>{a.initialEquity=this.equity(a);a.cost=a.shares.map((_,i)=>this.stocks[i].start);});this.player.cost.fill(0);this.people.forEach(a=>Object.assign(a,{shorts:[0,0,0,0,0],shortCost:[0,0,0,0,0],shortPending:[0,0,0,0,0],coverPending:[0,0,0,0,0],lent:[0,0,0,0,0],shortQuantity:0,lentQuantity:0,shortFees:0,totalDividends:0,lendingIncome:0}));this.stocks.forEach((s,i)=>s.index=i);this.lending=new SecuritiesLending(this);economics.init(this,economyVolatility);this.initialCash=this.people.reduce((s,a)=>s+a.cash,0);this.equityHistory=[this.player.cash];
  this.stocks.forEach(s=>s.candles.push(this.emptyBar(s,0)));this.stocks.forEach(s=>s.history=[s.price]);
  // Opening liquidity is two-sided and passive; the reference price is not moved by a fabricated opening trade.
  this.speedAgents=this.agents.filter(a=>a.type===6);this.normalActors=this.agents;
  this.initializing=true;this.agents.filter(a=>a.type===3).forEach(a=>{for(let i=0;i<5;i++)this.makeMarket(a,i);});this.initializing=false;
  this.event('市场开盘',`${count} 位交易者入场：内幕 ${insider}、速度量化 ${speed}、分析量化 ${analyst}。普通交易者不读取内部估值。`);
 }
 random(){let t=this.seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;}
 shuffle(a){const r=[...a];for(let i=r.length-1;i>0;i--){const j=Math.floor(this.random()*(i+1));[r[i],r[j]]=[r[j],r[i]];}return r;}
 event(title,body){this.eventArchive??=[];const e={id:this.eventArchive.length+1,tick:this.tick,title,body};this.eventArchive.push(e);this.events.unshift(e);this.events=this.events.slice(0,100);}
 emptyBar(s,tick){return {tick,open:s.price,high:s.price,low:s.price,close:s.price,volume:0,turnover:0,trades:0,vwap:s.price,complete:tick===0};}
 currentBar(i){const s=this.stocks[i];if(this.inTick||this.initializing)return s.candles.at(-1);if(!s.pendingBar){s.previous=s.candles.at(-1).close;s.pendingBar=this.emptyBar(s,this.tick+1);s.pendingBar.open=s.candles.at(-1).close;s.pendingBar.high=Math.max(s.pendingBar.open,s.price);s.pendingBar.low=Math.min(s.pendingBar.open,s.price);s.volume=0;s.turnover=0;}return s.pendingBar;}
 gross(a){if(!a.lentQuantity)return a.cash+a.shares.reduce((v,q,i)=>v+q*this.stocks[i].price,0);return a.cash+a.shares.reduce((s,q,i)=>s+(q+(a.lent?.[i]||0))*this.stocks[i].price,0);}
 shortValue(a){if(!a.shortQuantity)return 0;return (a.shorts||[]).reduce((v,q,i)=>v+q*this.stocks[i].price,0);}
 changeCash(a,amount){const before=a.cash,oldDebt=a.debt;if(amount<0&&a.cash+amount<this.reservedCash(a.id)-1e-7)this.cancelAll(a.id);if(a.cash+amount<0){const funding=-(a.cash+amount);a.debt+=funding;this.bankCash-=funding;a.cash=0;}else a.cash+=amount;return {cashDelta:a.cash-before,debtDelta:a.debt-oldDebt};}
 analysisContext(i){const s=this.stocks[i];return {company:this.company(i),supply:s.supply,start:s.start,economyFactor:this.economy.factor};}
 company(i){return economics.publicCompany(this,this.stocks[i]);}
 equity(a){return this.gross(a)-a.debt-this.shortValue(a);}
 investment(a){return this.equity(a)-a.initialEquity-a.totalIncome;}
 recordAccount(type,amount,cashDelta,debtDelta,details={}){this.accountLedger??=[];const p=this.player;this.accountLedger.push({id:this.accountLedger.length+1,tick:this.tick,phase:this.phase,type,amount,cashDelta,debtDelta,cash:p.cash,debt:p.debt,equity:this.equity(p),realized:p.realized,details});}
 ranking(mode='equity'){const rows=this.people.map(a=>({id:a.id,name:a.name,type:a.type,equity:this.equity(a),debt:a.debt,returnPct:(this.equity(a)/a.initialEquity-1)*100,tradingReturnPct:this.investment(a)/a.initialEquity*100}));const key=mode==='return'?'returnPct':mode==='trading'?'tradingReturnPct':'equity';return rows.sort((a,b)=>b[key]-a[key]||a.id-b.id).map((r,i)=>({...r,rank:i+1}));}
 margin(id=this.playerId){const p=this.people[id],gross=this.gross(p),equity=this.equity(p),shortValue=this.shortValue(p),liabilities=p.debt+shortValue;return {shortValue,liabilities,maintenance:Math.min(this.maintenance,.75/p.leverageLimit),recovery:p.leverageLimit<=3?this.recovery:Math.min(this.recovery,.9/p.leverageLimit),debt:p.debt,gross,equity,limit:p.leverageLimit,ratio:gross>0?equity/gross:1,leverage:equity>0?gross/equity:null,capacity:p.liquidating?0:Math.max(0,(p.leverageLimit-1)*equity-liabilities),interest:p.debt*this.loanRate,liquidating:p.liquidating};}

 setLeverage(v){if(!Number.isInteger(v)||v<1||v>100)return {ok:false,message:'融资上限须为 1–100 倍整数。'};if(this.player.debt+this.shortValue(this.player)>(v-1)*Math.max(0,this.equity(this.player))+1e-7)return {ok:false,message:'先还款或平空，再降低融资上限。'};this.player.leverageLimit=v;return {ok:true,message:`融资上限已设为 ${v}×。`};}
 borrow(amount,id=this.playerId){if(!Number.isFinite(amount)||amount<.01)return {ok:false,message:'借款金额至少 $0.01。'};amount=round(amount);const m=this.margin(id);if(m.liquidating||m.equity<=0||amount>m.capacity+1e-7)return {ok:false,message:'超过可借额度，或账户正在强平。'};const p=this.people[id];p.cash+=amount;p.debt+=amount;this.bankCash-=amount;if(id===this.playerId)this.recordAccount('borrow',amount,amount,amount);return {ok:true,amount,message:`已借入 $${amount.toFixed(2)}，净资产不变。`};}
 repay(amount,id=this.playerId){if(!Number.isFinite(amount)||amount<.01)return {ok:false,message:'还款金额至少 $0.01。'};const p=this.people[id],paid=Math.min(round(amount),p.debt,this.availableCash(p.id));if(paid<1e-7)return {ok:false,message:'没有可用现金或没有负债。'};p.cash-=paid;p.debt-=paid;this.bankCash+=paid;if(p.debt<1e-7)p.debt=0;if((!p.debt&&!this.shortValue(p))||this.margin(id).ratio>=this.margin(id).recovery)p.liquidating=false;if(id===this.playerId)this.recordAccount('repay',paid,-paid,-paid);return {ok:true,amount:paid,message:`已还款 $${paid.toFixed(2)}。`};}
 get orders(){return this.orderIndex?.values()||[];}
 set orders(list){this.orderIndex=new OrderIndex(this.count+1);for(const o of list)this.orderIndex.add(o);}
 reservedCash(id){return Math.max(0,this.orderIndex.cash[id]+((this.batch||this.pendingBatch)?.cash[id]||0));}
 reservedShares(id,i){return Math.max(0,this.orderIndex.shares[id*5+i]+((this.batch||this.pendingBatch)?.shares[id*5+i]||0)+(this.lending?.reserved(id,i)||0));}
 availableCash(id){return Math.max(0,this.people[id].cash-this.reservedCash(id));}
 availableShares(id,i){return Math.max(0,this.people[id].shares[i]-this.reservedShares(id,i));}
 cancel(id,owner=this.playerId){const o=this.orderIndex.active.get(id);return o?.owner===owner?this.orderIndex.remove(id):false;}
 cancelAll(owner=this.playerId){if(!this.batch)return this.orderIndex.cancelAll(owner);if(this.batch.cancelled.has(owner))return 0;const cash=this.orderIndex.cash[owner],shares=Array.from({length:5},(_,i)=>this.orderIndex.shares[owner*5+i]);this.batch.cancelled.set(owner,{cash,shares});this.batch.cash[owner]-=cash;shares.forEach((q,i)=>this.batch.shares[owner*5+i]-=q);return this.orderIndex.owners.get(owner)?.size||0;}
 book(i){return this.orderIndex.book(i);}
 execute(buy,sell,price){const i=buy.stock,qty=Math.min(buy.qty,sell.qty),amount=qty*price,b=this.people[buy.owner],s=this.people[sell.owner],stock=this.stocks[i];const old=b.shares[i]+b.lent[i]-b.shortPending[i];if(buy.intent!=='cover')b.cost[i]=(b.cost[i]*old+amount)/(old+qty);if(sell.intent==='short'){const sold=s.shorts[i]-s.shortPending[i];s.shortCost[i]=(s.shortCost[i]*sold+amount)/(sold+qty);s.shortPending[i]-=qty;}else s.realized+=qty*(price-s.cost[i]);b.cash-=amount;s.cash+=amount;b.shares[i]+=qty;s.shares[i]-=qty;buy.qty-=qty;sell.qty-=qty;this.orderIndex.fill(buy,qty);this.orderIndex.fill(sell,qty);if(buy.intent==='cover'){b.realized+=qty*(b.shortCost[i]-price);this.lending.close(b.id,i,qty);b.coverPending[i]-=qty;if(!b.shorts[i])b.shortCost[i]=0;}if(!s.shares[i]&&!s.lent[i])s.cost[i]=0;
  const bar=this.currentBar(i);stock.price=price;stock.volume+=qty;stock.turnover+=amount;this.lastTrades++;bar.high=Math.max(bar.high,price);bar.low=Math.min(bar.low,price);bar.close=price;bar.volume+=qty;bar.turnover+=amount;bar.trades++;bar.vwap=bar.turnover/bar.volume;
  // Only the mutable current candle changes; prior candles are never rewritten.
  if(this.inTick||this.initializing)stock.history[stock.history.length-1]=price;this.tradeArchive??=[];const t={id:this.tradeArchive.length+1,tick:bar.tick,stock:i,price,qty,buyer:b.id,seller:s.id,buyerIntent:buy.intent||'buy',sellerIntent:sell.intent||'sell',phase:this.phase};this.tradeArchive.push(t);this.trades.unshift(t);if(this.trades.length>1000)this.trades.length=1000;if(b.id===this.playerId||s.id===this.playerId){this.playerTrades.unshift(t);this.recordAccount(b.id===this.playerId?(buy.intent==='cover'?'cover':'buy'):(sell.intent==='short'?'short_sell':'sell'),amount,b.id===this.playerId?-amount:amount,0,{tradeId:t.id,symbol:stock.symbol,qty,price,buyer:b.id,seller:s.id,candleTick:bar.tick});}
 }
 matchIncoming(order){const side=order.side==='buy'?'sell':'buy';while(order.qty){const resting=this.orderIndex.best(order.stock,side,order.owner);if(!resting||(order.side==='buy'?resting.price>order.price:resting.price<order.price))break;this.execute(order.side==='buy'?order:resting,order.side==='sell'?order:resting,resting.price);}}
 place(id,i,side,qty,price,ttl=8,kind='limit'){
  if(!Number.isInteger(id)||!this.people[id]||!Number.isInteger(i)||!this.stocks[i]||!['buy','sell'].includes(side)||!Number.isSafeInteger(qty)||qty<1||!Number.isFinite(price)||price<.01||price>1e7||!Number.isInteger(ttl)||ttl<1||ttl>1000)return {ok:false,message:'交易参数无效：整股、正价格、有效期 1–1000 刻。'};
  price=round(price);if(side==='buy'&&this.people[id].liquidating)return {ok:false,message:'强平中不能买入。'};if(side==='buy'&&qty*price>this.availableCash(id)+1e-7)return {ok:false,message:'可用现金不足。'};if(side==='sell'&&qty>this.availableShares(id,i))return {ok:false,message:'可卖持仓不足。'};
  const order={id:++this.orderId,owner:id,stock:i,side,qty,original:qty,price,tick:this.tick,expires:this.tick+ttl,kind};if(this.batch){this.batch.orders.push(order);if(side==='buy')this.batch.cash[id]+=qty*price;else this.batch.shares[id*5+i]+=qty;return {ok:true,order,filled:0};}this.matchIncoming(order);this.orderIndex.add(order);return {ok:true,order,filled:qty-order.qty};
 }
 trade(id,i,side,qty,kind='market',price=0,ttl=30){
  if(!this.people[id]||!Number.isInteger(i)||!this.stocks[i]||!['buy','sell'].includes(side)||!Number.isSafeInteger(qty)||qty<1||!['market','limit'].includes(kind))return {ok:false,message:'无效交易参数。'};
  if(side==='buy'&&this.people[id].liquidating)return {ok:false,message:'强平中不能买入。'};
  let result;
  if(kind==='limit'){result=this.place(id,i,side,qty,Number(price),ttl,kind);if(!result.ok)return result;}
  else{const opposite=this.orderIndex.iterate(i,side==='buy'?'sell':'buy');let remaining=qty,total=0,limit=0;for(const o of opposite){if(o.owner===id)continue;const q=Math.min(remaining,o.qty);total+=q*o.price;limit=o.price;remaining-=q;if(!remaining)break;}const fill=qty-remaining;if(!fill)return {ok:false,message:'没有其他交易者的对手盘。'};if(side==='buy'&&total>this.availableCash(id)+1e-7)return {ok:false,message:'可用美元不足，请减少数量。'};if(side==='sell'&&qty>this.availableShares(id,i))return {ok:false,message:'可卖持仓不足。'};
   const order={id:++this.orderId,owner:id,stock:i,side,qty:fill,original:fill,price:limit,tick:this.tick,expires:this.tick+1,kind};this.matchIncoming(order);result={ok:true,order,filled:fill-order.qty};}
  if(id===this.playerId&&!this.checkingMargin)this.checkMargin();this.equityHistory[this.tick]=this.equity(this.player);return {ok:true,filled:result.filled,orderId:result.order.qty&&kind==='limit'?result.order.id:null,remaining:kind==='limit'?result.order.qty:qty-result.filled,message:`${side==='buy'?'买入':'卖出'} ${this.stocks[i].symbol}：成交 ${result.filled} 股${kind==='limit'&&result.order.qty?'，剩余挂单 '+result.order.qty+' 股':''}。`};
 }
 submit(i,side,qty,kind,price,ttl=30){return this.trade(this.playerId,i,side,qty,kind,price,ttl);}
 shortTrade(id,i,qty,price=0,cover=false){
  const a=this.people[id];if(!a||!this.stocks[i]||!Number.isSafeInteger(qty)||qty<1||!Number.isFinite(price)||price<0||(price>0&&price<.01)||price>1e7)return {ok:false,message:'做空/平空参数无效。'};
  if(!cover&&(a.liquidating||this.equity(a)<=0))return {ok:false,message:'强平中不能增加空头。'};
  if(cover&&qty>a.shorts[i]-a.coverPending[i])return {ok:false,message:'平空股数超过未平仓空头。'};
  let limit=price,requested=qty,quoteTotal=0;if(!limit){let left=qty;for(const o of this.orderIndex.iterate(i,cover?'sell':'buy')){if(o.owner===id)continue;const n=Math.min(left,o.qty);quoteTotal+=n*o.price;limit=o.price;left-=n;if(!left)break;}requested-=left;if(!requested)return {ok:false,message:'没有真实对手盘。'};}
  const mark=Math.max(this.stocks[i].price,limit);if(!cover&&requested*mark>this.margin(id).capacity+1e-7)return {ok:false,message:'空头额度不足，请提高杠杆上限或减小数量。'};
  if(cover&&(price||this.batch?requested*limit:quoteTotal)>this.availableCash(id)+1e-7)return {ok:false,message:'平空所需可用现金不足。'};
  const n=cover?requested:this.lending.open(id,i,requested);if(!n)return {ok:false,message:'借股池没有可借股票。'};
  if(cover)a.coverPending[i]+=n;else if(id===this.playerId)this.recordAccount('borrow_stock',0,0,0,{symbol:this.stocks[i].symbol,qty:n});
  const order={id:++this.orderId,owner:id,stock:i,side:cover?'buy':'sell',qty:n,original:n,price:round(limit),tick:this.tick,expires:this.tick+1,kind:'ioc',intent:cover?'cover':'short'};
  if(this.batch){this.batch.orders.push(order);if(cover)this.batch.cash[id]+=n*order.price;else this.batch.shares[id*5+i]+=n;return {ok:true,order,filled:0};}
  this.matchIncoming(order);const filled=n-order.qty;this.finishIOC(order);if(!this.checkingMargin)this.checkMargin(id);return {ok:filled>0,filled,remaining:qty-filled,orderId:0,message:`${cover?'买回平空':'借股卖空'} ${this.stocks[i].symbol}：成交 ${filled} 股，剩余取消。`};
 }
 finishIOC(o){this.orderIndex.remove(o.id);const a=this.people[o.owner];if(o.owner!==this.playerId)a.action=`${o.intent==='cover'?'平空':'做空'} ${this.stocks[o.stock].symbol} · 成交 ${o.original-o.qty} 股${o.qty?' · 剩余取消':''}`;if(o.intent==='short'&&o.qty){const returned=this.lending.close(o.owner,o.stock,o.qty);a.shortPending[o.stock]-=returned;}if(o.intent==='cover')a.coverPending[o.stock]-=o.qty;if(!a.shorts[o.stock])a.shortCost[o.stock]=0;}
 checkMargin(id=this.playerId){
  if(this.checkingMargin)return;const p=this.people[id],m=this.margin(id);if(!m.liabilities||(!m.liquidating&&m.equity>0&&m.ratio>=m.maintenance))return;
  this.checkingMargin=true;const oldPhase=this.phase;this.phase='liquidation';
  try{if(id===this.playerId&&!p.liquidating)this.event('保证金不足，开始减仓',`真实买盘卖出多头、真实卖盘买回空头；恢复到 ${(m.recovery*100).toFixed(2)}% 后停止。`);p.liquidating=true;this.cancelAll(id);
   for(let attempts=0;attempts<10000;attempts++){const now=this.margin(id);if(!now.liabilities||now.ratio>=now.recovery)break;let covered=false;
    for(let i=0;i<5;i++){if(!p.shorts[i])continue;const ask=this.orderIndex.best(i,'sell',id);if(!ask)continue;const need=Math.max(1,Math.ceil((now.gross-now.equity/now.recovery)/ask.price)),q=Math.min(p.shorts[i],ask.qty,need,Math.floor(this.availableCash(id)/ask.price));if(q>0){const r=this.shortTrade(id,i,q,ask.price,true);if(r.filled){covered=true;break;}}}
    if(covered)continue;const cash=this.availableCash(id),keep=this.shortValue(p);if(p.debt&&cash>keep+.01){this.repay(cash-keep,id);continue;}
    let candidate=null;for(let i=0;i<5;i++){if(!this.availableShares(id,i))continue;const bid=this.orderIndex.best(i,'buy',id);if(bid&&(!candidate||bid.qty*bid.price>candidate.bid.qty*candidate.bid.price))candidate={i,bid};}if(!candidate)break;
    const {i,bid}=candidate,mark=this.stocks[i].price,net=p.shares[i]+p.lent[i]-p.shorts[i],postEquity=now.equity+net*(bid.price-mark),postGross=now.gross+(p.shares[i]+p.lent[i])*(bid.price-mark),needed=postEquity>0?Math.ceil((postGross-postEquity/now.recovery)/bid.price):this.availableShares(id,i),q=Math.max(1,Math.min(this.availableShares(id,i),bid.qty,needed,p.debt?Math.ceil(p.debt/bid.price):Infinity));
    const r=this.trade(id,i,'sell',q,'market');if(!r.filled)break;const spare=this.availableCash(id)-this.shortValue(p);if(p.debt&&spare>.01)this.repay(spare,id);
   }
   if(!this.margin(id).liabilities||this.margin(id).ratio>=this.margin(id).recovery){p.liquidating=false;if(id===this.playerId)this.event('保证金恢复','真实成交已恢复比例，停止强平。');}
  }finally{this.phase=oldPhase;this.checkingMargin=false;}
 }

 reference(i){const s=this.stocks[i],completed=s.candles.slice(-6).filter(b=>b.complete).slice(-5);const sum=completed.reduce((a,b)=>a+b.turnover,0),volume=completed.reduce((a,b)=>a+b.volume,0);return volume?sum/volume:completed.at(-1)?.close??s.start;}
 indicators(i,withBook=true){const s=this.stocks[i],cacheKey=`${this.tick}:${this.inTick}`;if(s.technicalCache?.key===cacheKey){const result={...s.technicalCache.value};if(withBook)result.imbalance=this.imbalance(i);return result;}const bars=s.candles.slice(-61).filter(b=>b.complete),h=bars.slice(-60).map(b=>b.close),p=h.at(-1)||s.price;const sma=n=>h.slice(-n).reduce((a,b)=>a+b,0)/Math.min(n,h.length);let ema=p;if(h.length){ema=h[0];for(const v of h)ema+=2/13*(v-ema);}const returns=h.slice(1).map((v,k)=>Math.log(v/h[k])),mean=returns.length?returns.reduce((a,b)=>a+b,0)/returns.length:0,vol=returns.length?Math.sqrt(returns.reduce((a,b)=>a+(b-mean)**2,0)/returns.length):0;
  let up=0,down=0;for(let k=Math.max(1,h.length-14);k<h.length;k++){const d=h[k]-h[k-1];up+=Math.max(0,d);down+=Math.max(0,-d);}const rsi=up+down?100*up/(up+down):50;
  const recent=h.slice(-24).map(Math.log),n=recent.length,mx=(n-1)/2,my=n?recent.reduce((a,b)=>a+b,0)/n:0;let cov=0,vx=0,vy=0;recent.forEach((v,k)=>{cov+=(k-mx)*(v-my);vx+=(k-mx)**2;vy+=(v-my)**2;});const slope=vx?cov/vx:0,r2=vx&&vy?cov*cov/(vx*vy):0;
  const mu=sma(20),sd=Math.sqrt(h.slice(-20).reduce((a,b)=>a+(b-mu)**2,0)/Math.min(20,h.length));const result={sma5:sma(5),sma20:mu,ema12:ema,rsi14:rsi,volatility:vol,regressionSlope:slope,regressionR2:r2,bollingerUpper:mu+2*sd,bollingerLower:mu-2*sd,zScore:sd?(p-mu)/sd:0,imbalance:0,momentum:h.length>5?p/h[h.length-6]-1:0};s.technicalCache={key:cacheKey,value:result};return {...result,imbalance:withBook?this.imbalance(i):0};
 }
 imbalance(i){let bq=0,sq=0,n=0;for(const o of this.orderIndex.iterate(i,'buy')){bq+=o.qty;if(++n===10)break;}n=0;for(const o of this.orderIndex.iterate(i,'sell')){sq+=o.qty;if(++n===10)break;}return bq+sq?(bq-sq)/(bq+sq):0;}
 makeMarket(a,i){const ref=this.reference(i),eq=Math.max(1,this.equity(a)),weight=a.shares[i]*ref/eq,shift=clamp((.10-weight)*.025,-.0075,.0075),anchor=this.stocks[i].publicValue*Math.exp(this.initializing?0:a.valuationBias),center=Math.exp(.65*Math.log(anchor)+.35*Math.log(ref)+shift),spread=.0025+this.stocks[i].volatility*.06,qty=Math.max(1,Math.floor(eq*(.005+this.random()*.012)/center));const bp=round(Math.max(.01,center*(1-spread))),sp=round(center*(1+spread));let n=0;const b=Math.min(qty,Math.floor(this.availableCash(a.id)/bp)),q=Math.min(qty,this.availableShares(a.id,i));if(b>0){this.place(a.id,i,'buy',b,bp,3);n++;}if(q>0){this.place(a.id,i,'sell',q,Math.max(bp+.01,sp),3);n++;}a.action=`做市 ${this.stocks[i].symbol} · 双边 ${n} 单`;return n;}

 decide(a){if(a.liquidating){a.action='强平等待买盘';this.activity.wait++;this.actionSequence.push({id:a.id,phase:this.phase});return;}this.actionSequence.push({id:a.id,phase:this.phase});if(a.type===7)return analystTrader.decide(this,a);if(a.debt&&this.availableCash(a.id)-this.shortValue(a)>.01)this.repay(this.availableCash(a.id)-this.shortValue(a),a.id);if(this.random()>(a.type===6?.94:.78)){a.action='等待';this.activity.wait++;return;}let i=a.type===5?a.knownSymbols[Math.floor(this.random()*a.knownSymbols.length)]:this.random()<.6?a.focus:Math.floor(this.random()*5);if(a.type===7&&this.random()<.75){let best=-Infinity;for(let j=0;j<5;j++){const stock=this.stocks[j],f=forecast(a.analystStyle,this.indicators(j),this.reference(j),stock.publicValue*Math.exp(a.valuationBias),a.risk,this.analysisContext(j));const score=Math.abs(f.signal)*f.confidence-Math.max(0,this.loanRate)*f.horizon*.25-f.volatility;if(score>best){best=score;i=j;}}}if(a.type===5||a.type===7){for(let j=0;j<5;j++)if(a.shorts[j]&&(this.stocks[j].price<a.shortCost[j]*.96||this.stocks[j].price>a.shortCost[j]*(a.type===7?1.06:1.1))){i=j;break;}}const s=this.stocks[i],ref=this.reference(i);
  if(a.type===3){this.cancelAll(a.id);if(this.makeMarket(a,i)){this.activity.buy++;this.activity.sell++;}else this.activity.wait++;return;}
  const ind=this.indicators(i,a.type===6||a.type===7),noise=(this.random()-.5)*s.volatility*(.35+a.risk),publicTarget=s.publicValue*Math.exp(a.valuationBias);let target=ref;
  if(a.type===0)target=publicTarget*Math.exp(noise*.35);if(a.type===1)target=ref*Math.exp(ind.momentum*.65+noise*.4);if(a.type===2)target=ref*Math.exp(-ind.momentum*.55+noise*.4);if(a.type===4)target=ref*Math.exp(noise+a.bias*.003);if(a.type===5){target=s.fair*Math.exp(noise*.08);a.analysis='掌握对应公司最新经营现金流、需求和利润率；不是未来成交价';}
  if(a.type===6){this.cancelAll(a.id);const bid=this.orderIndex.best(i,'buy',a.id),ask=this.orderIndex.best(i,'sell',a.id),micro=bid&&ask?(ask.price*bid.qty+bid.price*ask.qty)/(bid.qty+ask.qty):ref;target=micro*Math.exp(clamp(ind.imbalance*.006+ind.momentum*.4+ind.regressionSlope*2,-.025,.025));a.analysis='微价格 + 实时盘口 + 趋势 · 每刻两次机会';}
  let model=null;if(a.type===7){model=forecast(a.analystStyle||ANALYST_STYLES[0],ind,ref,publicTarget,a.risk,this.analysisContext(i));target=ref*Math.exp(model.signal);a.analysis=`${a.analystStyle||ANALYST_STYLES[0]} · ${model.signal>=0?'看涨':'看跌'} · 财报/走势 ${(model.signal*100).toFixed(2)}% · 比较五股机会`;}
  const directional=Math.log(target/ref),probability=i===a.focus?(this.riskResults?.[a.id*2]??.5):(model?.confidence??.58);
  if((a.type===5||a.type===7)&&a.shorts[i]){const takeProfit=s.price<a.shortCost[i]*.96,stopLoss=s.price>a.shortCost[i]*(a.type===7?1.06:1.1);if(directional>=-.001||takeProfit||stopLoss){const ask=this.orderIndex.best(i,'sell',a.id),q=ask?Math.min(a.shorts[i],Math.floor(this.availableCash(a.id)/ask.price),ask.qty):0;if(q){const r=this.shortTrade(a.id,i,q,ask.price,true);a.action=`平空 ${s.symbol} ${q} 股`;this.activity[r.ok?'buy':'wait']++;return;}}}
  if((a.type===5||a.type===7)&&directional<-.004&&this.availableShares(a.id,i)===0){const confidence=model?Math.min(model.confidence,i===a.focus?1-probability:model.confidence):1-probability,shortPolicy=policy({type:a.type,risk:a.risk,signal:-directional,volatility:ind.volatility,probUp:confidence,loanRate:this.lending.rate+(model?.dividendYield||0)/12,cashRate:-this.cashRate,horizon:model?.horizon,ceiling:model?.ceiling}),eq=Math.max(1,this.equity(a));
   if(shortPolicy.qualified&&a.usesLoans&&this.random()<a.loanPreference){a.leverageLimit=Math.min(100,Math.max(2,Math.ceil(shortPolicy.target),Math.ceil(1+(a.debt+this.shortValue(a))/eq)));const cap=eq*(model?.shortExposure||.4)*shortPolicy.target/5-a.shorts[i]*ref,price=Math.max(.01,round(ref*Math.exp(directional)*.998)),q=Math.min(Math.floor(Math.max(0,cap)/price),Math.floor(this.margin(a.id).capacity/Math.max(s.price,price)),this.lending.available(a.id,i));if(q){const r=this.shortTrade(a.id,i,q,price,false);a.action=r.ok?`做空 ${s.symbol} ${r.order?.original||r.filled} 股`:'借股不足';this.activity[r.ok?'sell':'wait']++;return;}}
  }
  const signal=Math.log(target/ref),eq=Math.max(1,this.equity(a)),exposure=model?.exposure??(.35+a.risk*.3),desired=eq*exposure/5,inventory=(desired-a.shares[i]*ref)/Math.max(1,eq/5);const prob=clamp(.5+signal*(a.type>=5?10:5)+inventory*.35,.03,.97),side=this.random()<prob?'buy':'sell';
  const spread=a.type===6?.0002+this.random()*.0004:.001+this.random()*.002,price=round(Math.max(.01,target*(1+(side==='buy'?-1:1)*spread)));
  const riskScale=this.riskResults?.[a.id*2+1]??1,probUp=this.riskResults?.[a.id*2]??.5,allocation=(a.type===5?.12:a.type>=6?.08:.025)+this.random()*(a.type>=5?.18:.12);
  // Risk samples describe focus only; analysts use their own per-symbol model off focus.
  const confidence=model?Math.min(model.confidence,i===a.focus?probUp:model.confidence):i===a.focus?probUp:Math.min(probUp,.58),finance=policy({type:a.type,risk:a.risk,signal,volatility:ind.volatility,probUp:confidence,loanRate:this.loanRate,cashRate:this.cashRate,horizon:model?.horizon,ceiling:model?.ceiling});
  const strong=finance.qualified,financeAllowed=a.usesLoans&&strong&&this.random()<a.loanPreference;
  const targetLeverage=financeAllowed?finance.target:1;
  // Never lower the contract below outstanding debt; no retrospective margin tightening.
  a.leverageLimit=Math.min(100,Math.max(Math.ceil(targetLeverage),Math.ceil(1+(a.debt+this.shortValue(a))/eq),1));
  const positionCap=model?eq*exposure*targetLeverage/5:a.type===5?eq*.5*targetLeverage:a.type===6?eq*.25*targetLeverage:desired*1.5;
  const positionBudget=Math.max(0,positionCap-a.shares[i]*ref);
  const requested=Math.min(eq*allocation*riskScale*targetLeverage*(model?.aggression||1),positionBudget);
  let budget=Math.min(Math.max(0,this.availableCash(a.id))*.65,requested),qty;
  if(side==='buy'&&financeAllowed){const shortfall=requested-this.availableCash(a.id),capacity=this.margin(a.id).capacity,targetDebt=Math.max(0,(targetLeverage-1)*eq-a.debt);if(shortfall>.01&&capacity>.01){const amount=Math.min(shortfall,capacity,targetDebt);if(amount>=.01)this.borrow(Math.floor(amount*100)/100,a.id);budget=Math.min(requested,this.availableCash(a.id));}}
  qty=side==='buy'?Math.min(Math.floor(budget/price),Math.floor(this.availableCash(a.id)/price)):Math.min(Math.max(1,Math.floor((eq*allocation*riskScale*(model?.aggression||1)+Math.max(0,a.shares[i]*ref-desired)*.5+eq*Math.max(0,-signal)*2)/price)),this.availableShares(a.id,i));
  if(!qty){a.action='等待';this.activity.wait++;return;}const r=this.place(a.id,i,side,qty,price,a.type===6?1:2+Math.floor(this.random()*7));a.action=r.ok?`${side==='buy'?'买':'卖'} ${s.symbol} ${qty} 股${r.filled?' · 成交 '+r.filled:''}`:'等待';this.activity[r.ok?side:'wait']++;
  if(a.debt&&(!strong||side==='sell')&&this.availableCash(a.id)-this.shortValue(a)>.01)this.repay(this.availableCash(a.id)-this.shortValue(a),a.id);
 }
 beginTick(deferSpeed=false){if(this.people.some(a=>Math.max(a.cash,a.debt)>1e100/1.5)||this.stocks.some(s=>Math.max(s.company.cash,s.company.debt)>1e100/1.5))throw new Error('金额超出本局数值范围，请使用较低的极端利率重新开局。');this.tickStarted=performance.now();if(this.inTick)throw new Error('上一回合尚未结束。');this.tick++;this.inTick=true;this.phase='opening';this.lastTrades=0;this.activity={buy:0,sell:0,wait:0};this.actionSequence=[];
  this.stocks.forEach(s=>{s.previous=s.candles.at(-1).close;const bar=s.pendingBar||this.emptyBar(s,this.tick);s.pendingBar=null;s.volume=bar.volume;s.turnover=bar.turnover;this.lastTrades+=bar.trades;s.candles.push(bar);s.history.push(s.price);});this.orderIndex.expire(this.tick);
  economics.step(this);this.lending.tick();
  this.people.forEach(a=>{const cashInterest=a.cash*this.cashRate,skillIncome=a.skill*this.economy.factor,income=cashInterest+skillIncome,d=this.changeCash(a,income);a.lastIncome=income;a.totalIncome+=income;this.minted+=income;if(a.id===this.playerId)this.recordAccount('income',income,d.cashDelta,d.debtDelta,{cashInterest,skillIncome,economyFactor:this.economy.factor});});for(const a of this.people){const interest=a.debt*this.loanRate;a.debt+=interest;a.financeCosts+=interest;if(interest&&a.id===this.playerId)this.recordAccount('loan_interest',interest,0,interest);if(a.debt||this.shortValue(a))this.checkMargin(a.id);}

  if(this.tick%18===0){const i=Math.floor(this.random()*5),s=this.stocks[i],sign=this.random()<.5?-1:1,shock=.025+this.random()*.045;s.company.demand=clamp(s.company.demand*Math.exp(sign*shock),.3,3);s.company.newsSentiment+=sign*shock;s.fair*=Math.exp(sign*shock);s.publicValue*=Math.exp(sign*shock*.35);this.event(`${s.symbol} 行业${sign>0?'利好':'利空'}`,`公开消息只反映方向和部分幅度；最新内部经营状态仅向掌握 ${s.symbol} 的内幕交易者开放。`);}
  this.stocks.forEach(s=>{s.fairHistory.push(s.fair);if(this.tick%36===0)s.publicValue=s.fairHistory[Math.max(0,this.tick-6)]*Math.exp((this.random()-.5)*.01);});
  if(this.tick%36===0)this.event('估值报告公布','公开估值根据六刻前的基本面更新，普通交易者可读取，内幕信息仍有时间优势。');
  if(!deferSpeed){const start=performance.now();this.riskResults=cpuRisk(this.riskInputs());this.performance={...this.performance,backend:'CPU',device:'CPU',riskMs:performance.now()-start};this.runSpeed();}
 }
 finishTick(){this.runBatch(this.normalActors,'normal');this.sealTick();}
 async finishTickAsync(){await this.runBatchAsync(this.normalActors,'normal');this.sealTick();}
 sealTick(){if(!this.inTick)throw new Error('没有待完成回合。');for(const a of this.people)if(a.debt||this.shortValue(a))this.checkMargin(a.id);this.stocks.forEach(s=>{const b=s.candles.at(-1);b.complete=true;b.close=s.price;b.vwap=b.volume?b.turnover/b.volume:b.close;});this.equityHistory[this.tick]=this.equity(this.player);this.inTick=false;this.phase='manual';this.performance.tickMs=performance.now()-this.tickStarted;
  if(!this.won&&this.equity(this.player)>=this.goalEquity&&this.investment(this.player)>=this.goalInvestment){this.won=true;this.event('投资目标达成',`扣除被动收入后的投资盈利达到 ${this.goalInvestment}，且净资产达到 ${this.goalEquity}。`);}
 }
 riskInputs(){const input=new Float64Array(this.count*4),refs=this.stocks.map((_,i)=>this.reference(i)),inds=this.stocks.map((_,i)=>this.indicators(i,false));for(const a of this.agents){const i=a.focus,s=this.stocks[i],ref=refs[i],ind=inds[i];let drift=Math.log(s.publicValue/ref)/12;if(a.type===5)drift=Math.log(s.fair/ref)/12;if(a.type===1||a.type===6)drift=ind.momentum/5;if(a.type===2)drift=-ind.momentum/5;if(a.type===7){const model=forecast(a.analystStyle||ANALYST_STYLES[0],ind,s.price,s.publicValue*Math.exp(a.valuationBias),a.risk,this.analysisContext(i));drift=model.signal/model.horizon;}input.set([clamp(drift,-.02,.02),Math.max(.002,ind.volatility),a.risk,(Math.imul(a.id+1,2654435761)+Math.imul(this.tick,2246822519))>>>0],a.id*4);}return input;}
 runSpeed(){this.runBatch(this.speedAgents,'speed');this.phase='player-bot';}
 async runSpeedAsync(){await this.runBatchAsync(this.speedAgents,'speed');this.phase='player-bot';}
 prepareBatch(actors,phase){if(this.batch||this.pendingBatch)throw new Error('撮合批次重叠。');this.phase=phase;this.batch={orders:[],cancelled:new Map(),cash:new Float64Array(this.people.length),shares:new Float64Array(this.people.length*5)};try{this.shuffle(actors).forEach(a=>this.decide(a));for(const [owner,released]of this.batch.cancelled){this.orderIndex.cancelAll(owner);this.batch.cash[owner]+=released.cash;released.shares.forEach((q,i)=>this.batch.shares[owner*5+i]+=q);}const resting=Array.from({length:5},()=>[]),incoming=Array.from({length:5},()=>[]);for(const o of this.orders)resting[o.stock].push(o);for(const o of this.batch.orders)incoming[o.stock].push(o);this.pendingBatch=this.batch;return {orders:this.batch.orders,tasks:resting.map((rows,i)=>({count:this.people.length,resting:rows,incoming:incoming[i]}))};}finally{this.batch=null;}}
 settleBatch(batch,plans){this.pendingBatch=null;for(const o of batch.orders)this.orderIndex.add(o);for(const fills of plans)for(const fill of fills){const buy=this.orderIndex.active.get(fill.buy),sell=this.orderIndex.active.get(fill.sell);if(!buy||!sell||Math.min(buy.qty,sell.qty)!==fill.qty)throw new Error('并行撮合结算数量不一致。');this.execute(buy,sell,fill.price);}for(const o of batch.orders)if(o.kind==='ioc')this.finishIOC(o);this.orderIndex.compactBooks();}
 runBatch(actors,phase){const batch=this.prepareBatch(actors,phase);this.settleBatch(batch,batch.tasks.map(matching.plan));}
 async runBatchAsync(actors,phase){const decisionStart=performance.now(),batch=this.prepareBatch(actors,phase),started=performance.now();this.performance.decisionMs=started-decisionStart;this.performance.batchOrders=batch.orders.length;let results;try{results=await matching.parallel(batch.tasks);}catch(error){this.performance.matchFallback=error.message;this.settleBatch(batch,batch.tasks.map(matching.plan));this.performance.matchBackend='CPU 单线程回退';this.performance.matchThreads=[];this.performance.matchWindows=[];this.performance.matchMs=performance.now()-started;return;}const settleStart=performance.now();this.settleBatch(batch,results.map(r=>r.fills));this.performance.settlementMs=performance.now()-settleStart;this.performance.batchFills=results.reduce((sum,r)=>sum+r.fills.length,0);delete this.performance.matchFallback;this.performance.matchBackend='CPU 工作线程 · 5 股并行';this.performance.matchThreads=results.map(r=>r.threadId);this.performance.matchMs=performance.now()-started;this.performance.matchWindows=results.map(r=>({threadId:r.threadId,start:r.start,end:r.end}));}
 step(){this.beginTick();this.finishTick();}
 candles(i,timeframe=1,count=240,offset=0){if(!Number.isInteger(timeframe)||timeframe<1||timeframe>1000)throw new Error('周期须为 1–1000 刻。');const stock=this.stocks[i],src=stock.pendingBar?[...stock.candles,stock.pendingBar]:stock.candles,result=[];for(const b of src){const bucket=Math.floor(b.tick/timeframe);let r=result.at(-1);if(!r||r.bucket!==bucket){r={bucket,tick:b.tick,endTick:b.tick,open:b.open,high:b.high,low:b.low,close:b.close,volume:0,turnover:0,trades:0,complete:true};result.push(r);}r.endTick=b.tick;r.high=Math.max(r.high,b.high);r.low=Math.min(r.low,b.low);r.close=b.close;r.volume+=b.volume;r.turnover+=b.turnover;r.trades+=b.trades;r.complete=b.complete&&b.tick%timeframe===timeframe-1;}result.forEach(b=>b.vwap=b.volume?b.turnover/b.volume:b.close);const end=Math.max(0,result.length-offset);return count===0?result.slice(0,end):result.slice(Math.max(0,end-count),end);}
 playerRanking(){const p=this.player,eq=this.equity(p),rt=eq/p.initialEquity-1,tr=this.investment(p)/p.initialEquity,ranks={equity:1,return:1,trading:1};for(const a of this.agents){const value=this.equity(a);if(value>eq||value===eq&&a.id<p.id)ranks.equity++;const r=value/a.initialEquity-1,t=(value-a.initialEquity-a.totalIncome)/a.initialEquity;if(r>rt||r===rt&&a.id<p.id)ranks.return++;if(t>tr||t===tr&&a.id<p.id)ranks.trading++;}return ranks;}
 uiOrders(){const result=new Map();for(let i=0;i<5;i++)for(const side of ['buy','sell']){let n=0;for(const o of this.orderIndex.iterate(i,side)){result.set(o.id,o);if(++n===200)break;}}for(const id of this.orderIndex.owners.get(this.playerId)||[])result.set(id,this.orderIndex.active.get(id));return [...result.values()];}
 uiLevels(){return this.stocks.map((_,i)=>{const result={buy:[],sell:[]};for(const side of ['buy','sell']){let last=null;for(const o of this.orderIndex.iterate(i,side)){if(last?.price!==o.price){if(result[side].length===5)break;last={price:o.price,qty:0};result[side].push(last);}last.qty+=o.qty;}}return result;});}
 snapshot(compact=false){return {compact,playerRanks:compact?this.playerRanking():undefined,bookLevels:compact?this.uiLevels():undefined,performance:this.performance,goalEquity:this.goalEquity,goalInvestment:this.goalInvestment,acceleration:this.acceleration,tick:this.tick,count:this.count,playerId:this.playerId,inTick:this.inTick,phase:this.phase,initialCash:this.initialCash,minted:this.minted,cashRate:this.cashRate,loanRate:this.loanRate,economy:{factor:this.economy.factor,volatility:this.economy.volatility},stockBorrowRate:this.lending.rate,lendingAvailable:[...this.lending.total],maintenance:this.maintenance,recovery:this.recovery,lastTrades:this.lastTrades,activity:this.activity,won:!!this.won,
  player:structuredClone(this.player),people:(compact?this.agents.slice(0,200):this.people).map(a=>({...a,knownSymbols:a.knownSymbols?.map(i=>this.stocks[i].symbol)})),stocks:this.stocks.map(s=>({symbol:s.symbol,sector:s.sector,price:s.price,color:s.color,start:s.start,supply:s.supply,company:this.company(s.index),publicValue:s.publicValue,previous:s.previous,volatility:s.volatility,volume:s.volume,turnover:s.turnover,history:(s.pendingBar?[...s.history,s.pendingBar.close]:s.history).slice(-240),candles:(s.pendingBar?[...s.candles,s.pendingBar]:s.candles).slice(-240),totalBars:s.candles.length+(s.pendingBar?1:0)})),orders:compact?this.uiOrders():this.orders,trades:this.trades.slice(0,80),playerTrades:this.playerTrades.slice(0,200),events:this.events.slice(0,24),margin:this.margin()};}
 summary(){return {tick:this.tick,cash:round(this.player.cash),availableCash:round(this.availableCash(this.playerId)),equity:round(this.equity(this.player)),debt:round(this.player.debt),investment:round(this.investment(this.player)),margin:this.margin(),shares:[...this.player.shares],stocks:this.stocks.map(s=>({symbol:s.symbol,price:s.price,publicValue:s.publicValue})),orders:this.orders.filter(o=>o.owner===this.playerId)};}
}
module.exports={Market,TYPES};
