'use strict';
const {spawn}=require('node:child_process'),path=require('node:path'),{cpuRisk}=require('./risk-model.cjs');
class GPU {
 constructor(){this.status={available:false,backend:'CPU',device:'正在检测独显'};this.child=null;this.buffer=Buffer.alloc(0);this.pending=null;this.queue=Promise.resolve();this.ready=null;}
 start(){if(this.ready)return this.ready;this.ready=new Promise(resolve=>{const child=this.child=spawn(process.env.MARKET_PYTHON||'python',['-u',path.join(__dirname,'cuda-worker.py')],{windowsHide:true,stdio:['pipe','pipe','pipe']});let settled=false;const done=status=>{if(settled)return;settled=true;clearTimeout(timer);this.status=status.available?status:{available:false,backend:'CPU',device:'CPU 回退',reason:status.error||'CUDA unavailable'};child.unref();child.stdout.unref?.();child.stderr.unref?.();child.stdin.unref?.();resolve(this.status);};const timer=setTimeout(()=>{done({error:'GPU 初始化超时'});child.kill();},30000);this.onFrame=frame=>{try{done(JSON.parse(frame));}catch{done({error:'GPU 握手失败'});}};child.stdout.on('data',chunk=>{this.buffer=Buffer.concat([this.buffer,chunk]);while(this.buffer.length>=4){const size=this.buffer.readUInt32LE(0);if(size>4*1024*1024){child.kill();break;}if(this.buffer.length<size+4)break;const frame=this.buffer.subarray(4,4+size);this.buffer=this.buffer.subarray(4+size);this.onFrame?.(frame);}});let error='';child.stderr.on('data',c=>error=(error+c).slice(-2000));child.on('error',e=>done({error:e.message}));child.on('exit',()=>{done({error:error||'GPU worker exited'});this.status={available:false,backend:'CPU',device:'CPU 回退',reason:error||'CUDA worker disconnected'};this.pending?.reject(new Error(this.status.reason));this.pending=null;});child.stdin.on('error',()=>{});});return this.ready;}
 async compute(input,mode='auto'){if(mode==='cpu')return {values:cpuRisk(input),backend:'CPU',ms:0};await this.start();if(!this.status.available){if(mode==='gpu')throw new Error(this.status.reason);return {values:cpuRisk(input),backend:'CPU',ms:0};}const task=()=>new Promise((resolve,reject)=>{this.child.stdout.ref?.();this.child.stdin.ref?.();const t=performance.now(),timer=setTimeout(()=>{this.child.kill();reject(new Error('GPU batch timed out'));},15000);this.pending={reject};this.onFrame=frame=>{clearTimeout(timer);this.child.stdout.unref?.();this.child.stdin.unref?.();this.pending=null;if(frame.length!==8+input.length*4){try{reject(new Error(JSON.parse(frame).error));}catch{reject(new Error('Invalid GPU result'));}return;}const values=new Float64Array(input.length/2);Buffer.from(values.buffer).set(frame.subarray(8));resolve({values,backend:'CUDA',ms:performance.now()-t,kernelMs:frame.readDoubleLE(0)});};const payload=Buffer.from(input.buffer,input.byteOffset,input.byteLength),header=Buffer.alloc(4);header.writeUInt32LE(payload.length);this.child.stdin.write(header);this.child.stdin.write(payload);});const job=this.queue.then(task,task);this.queue=job.catch(()=>{});try{return await job;}catch(e){if(mode==='gpu')throw e;this.status={available:false,backend:'CPU',device:'CPU 回退',reason:e.message};return {values:cpuRisk(input),backend:'CPU',ms:0};}}
 close(){this.child?.kill();}
}
const gpu=new GPU();module.exports={GPU,gpu};
