'use strict';
const http=require('node:http'),fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto'),{spawn}=require('node:child_process');const {GameSession}=require('./controller.cjs'),{findCompiler}=require('./bot-runtime.cjs');const {gpu}=require('./gpu-risk.cjs');
const root=path.join(__dirname,'dist'),sessions=new Map();let port=Number(process.env.MARKET_PORT)||8765;
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.hpp':'text/plain; charset=utf-8','.cpp':'text/plain; charset=utf-8','.md':'text/plain; charset=utf-8'};
const json=(res,data,status=200)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(data));};
async function body(req){if(!req.headers['content-type']?.startsWith('application/json'))throw new Error('请求必须使用 JSON。');let bytes=0,chunks=[];for await(const chunk of req){bytes+=chunk.length;if(bytes>2*1024*1024)throw new Error('请求过大。');chunks.push(chunk);}return JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}');}
const server=http.createServer(async(req,res)=>{try{const allowedHosts=[`127.0.0.1:${port}`,`localhost:${port}`];if(!allowedHosts.includes(req.headers.host)){json(res,{error:'只支持本机访问。'},403);return;}if(req.headers.origin&&!allowedHosts.some(h=>req.headers.origin===`http://${h}`)){json(res,{error:'不接受其他网站的操作请求。'},403);return;}const url=new URL(req.url,`http://127.0.0.1:${port}`),route=url.pathname;
 if(route==='/api/new'&&req.method==='POST'){const opts=await body(req),id=crypto.randomBytes(16).toString('hex'),session=new GameSession(id,{count:Number(opts.count??1000),seed:opts.seed===''||opts.seed===undefined?Date.now():Number(opts.seed),cashRate:opts.cashRate===undefined?.0001:Number(opts.cashRate),loanRate:opts.loanRate===undefined?.0005:Number(opts.loanRate),playerCash:opts.playerCash===undefined?10000:Number(opts.playerCash),acceleration:opts.acceleration||'auto'});if(session.market.acceleration==='gpu'&&!(await gpu.start()).available)throw new Error('没有可用独显 CUDA：'+gpu.status.reason);const oldId=url.searchParams.get('id'),old=sessions.get(oldId);if(old&&!old.busy&&!old.bot.compiling){old.bot.stop();sessions.delete(oldId);}sessions.set(id,session);json(res,{id,state:session.snapshot()});return;}
 if(route==='/api/gpu'){json(res,await gpu.start());return;}
 if(route==='/api/compiler'){const c=await findCompiler();json(res,{available:!!c,name:c?.name});return;}
 if(route==='/api/example'){json(res,{source:await fs.readFile(path.join(__dirname,'strategies','example.cpp'),'utf8')});return;}
 if(route.startsWith('/api/')){const session=sessions.get(url.searchParams.get('id'));if(!session){json(res,{error:'本局不存在，请重新开局。'},404);return;}
  if(route==='/api/state'){json(res,session.snapshot());return;}
  if(route==='/api/bot/source'){json(res,{source:session.bot.source});return;}
  if(route==='/api/history'){const data=session.rpc('get_history',{stock:url.searchParams.get('stock')||'A',timeframe:Number(url.searchParams.get('timeframe')||1),count:Number(url.searchParams.get('count')??240),offset:Number(url.searchParams.get('offset')||0)});json(res,data);return;}
  if(route==='/api/export'){const bars=session.rpc('get_history',{stock:url.searchParams.get('stock')||'A',timeframe:Number(url.searchParams.get('timeframe')||1),count:0});const keys=['tick','endTick','open','high','low','close','volume','turnover','trades','vwap','complete'];res.writeHead(200,{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':'attachment; filename="market-history.csv"'});res.end('\uFEFF'+keys.join(',')+'\n'+bars.map(b=>keys.map(k=>b[k]).join(',')).join('\n'));return;}
  if(req.method!=='POST'){json(res,{error:'未知请求。'},404);return;}const args=await body(req);
  if(route==='/api/pause'){session.batchStop=true;json(res,{ok:true});return;}
  if(route==='/api/batch'){json(res,await session.batch(args));return;}
  if(route==='/api/step'){const result=await session.step(args.runBot??session.bot.enabled);result.state.busy=false;json(res,result);return;}
  if(route==='/api/action'){if(session.busy||session.batching||session.bot.compiling)throw new Error('本刻程序尚未结束，暂不能手动交易。');const result=session.action(args.method,args.args);json(res,{result,state:session.snapshot()});return;}
  if(route==='/api/bot/compile'){if(session.busy||session.batching)throw new Error('请先停止本刻程序再编译。');const result=await session.bot.compile(args);json(res,{result,state:session.snapshot()});return;}
  if(route==='/api/bot/config'){if(args.enabled===false)session.bot.stop();else if(args.enabled===true){if(!session.bot.executable||session.bot.compiling)throw new Error('请先成功编译程序。');session.bot.enabled=true;}if(args.timeout!==undefined){const t=Number(args.timeout);if(!Number.isInteger(t)||t<1||t>120)throw new Error('每刻时间上限为 1–120 秒。');session.bot.timeout=t;}json(res,session.snapshot());return;}
  if(route==='/api/query'){json(res,session.rpc(args.method,args.args||{}));return;}json(res,{error:'未知接口。'},404);return;
 }
 let file;if(['/sdk/market.hpp','/sdk/README.md','/strategies/example.cpp'].includes(route))file=path.join(__dirname,route.slice(1));else{let decoded;try{decoded=decodeURIComponent(route);}catch{json(res,{error:'错误路径。'},400);return;}file=path.resolve(root,'.'+(decoded==='/'?'/index.html':decoded));if(!file.startsWith(root+path.sep)){json(res,{error:'禁止访问。'},403);return;}}
 const data=await fs.readFile(file);res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(data);
 }catch(error){json(res,{error:error.message},error.code==='ENOENT'?404:400);}});
server.on('error',err=>{if(err.code==='EADDRINUSE'&&port<8785){port++;server.listen(port,'127.0.0.1');}else{console.error(err.message);process.exitCode=1;}});server.on('listening',()=>{const url=`http://127.0.0.1:${port}`;console.log(`\n  MARKET STREET V3\n  Game ready: ${url}\n  Keep this window open while playing.\n  C++ programs run on this computer once per game tick.\n`);if(!process.argv.includes('--no-browser')){const child=spawn('powershell.exe',['-NoProfile','-Command',`Start-Process '${url}'`],{windowsHide:true,stdio:'ignore'});child.on('error',()=>{});}});
setInterval(()=>{const cutoff=Date.now()-6*3600000;for(const [id,s]of sessions)if(!s.busy&&!s.bot.compiling&&s.updated<cutoff){s.bot.stop();sessions.delete(id);}},60000).unref();server.listen(port,'127.0.0.1');
process.on('SIGINT',()=>{gpu.close();for(const s of sessions.values())s.bot.stop();server.close(()=>process.exit(0));});

gpu.start().then(status=>console.log(status.available?`  CUDA discrete GPU: ${status.device}`:`  CPU fallback: ${status.reason}`));
