'use strict';
const assert=require('node:assert/strict');
const base=process.env.MARKET_TEST_URL||'http://127.0.0.1:8765';
async function main(){const request=async(route,data,extra={})=>fetch(base+route,{...extra,method:data===undefined?'GET':'POST',headers:{...(data===undefined?{}:{'Content-Type':'application/json'}),...(extra.headers||{})},body:data===undefined?undefined:JSON.stringify(data)});
 assert.equal((await request('/api/new',{count:49})).status,400);const created=await (await request('/api/new',{count:50,seed:17})).json(),id=created.id;assert.equal(created.state.playerId,50);assert.equal(created.state.people.length,50);assert.equal(created.state.compact,true);const gpu=await (await request('/api/gpu')).json();if(gpu.available)assert.equal(gpu.discrete,true);const custom=await (await request('/api/new',{count:50,seed:17,playerCash:25000,cashRate:.0002,loanRate:.001,acceleration:'cpu'})).json();assert.equal(custom.state.player.cash,25000);assert.equal(custom.state.cashRate,.0002);assert.equal(custom.state.loanRate,.001);const customTick=await (await request('/api/step?id='+custom.id,{})).json();assert.equal(customTick.state.performance.backend,'CPU');assert.equal(customTick.state.player.cash,25008);assert.equal((await request('/api/new',{count:100001})).status,400);
 assert.equal((await request('/api/new',{count:50},{headers:{Origin:'https://example.com'}})).status,403);assert.equal((await request('/sdk/README.md')).status,200);assert.equal((await request('/sdk/market.hpp')).status,200);assert.equal((await request('/api/state?id=missing')).status,404);
 let res=await (await request('/api/action?id='+id,{method:'set_leverage',args:{value:3}})).json();assert.ok(res.result.ok);res=await (await request('/api/action?id='+id,{method:'borrow',args:{amount:20000}})).json();assert.equal(res.state.player.debt,20000);assert.equal(res.state.margin.equity,10000);
 const compiled=await (await request('/api/bot/compile?id='+id,{source:'#include "market.hpp"\n#include <thread>\n#include <chrono>\nint main(){market::memory_set("http",market::tick());std::this_thread::sleep_for(std::chrono::seconds(3));return 0;}'})).json();assert.ok(compiled.result?.ok,JSON.stringify(compiled));await request('/api/bot/config?id='+id,{enabled:true});const running=request('/api/step?id='+id,{});await new Promise(r=>setTimeout(r,200));const state=await (await request('/api/state?id='+id)).json();assert.ok(state.busy&&state.bot.running&&state.inTick);assert.equal(state.phase,'player-bot');assert.equal((await request('/api/action?id='+id,{method:'borrow',args:{amount:1}})).status,400);assert.equal((await request('/api/step?id='+id,{})).status,400);await request('/api/bot/config?id='+id,{enabled:false});const ended=await (await running).json();assert.equal(ended.state.busy,false);assert.equal(ended.state.inTick,false);assert.equal(ended.state.bot.enabled,false);assert.equal(ended.state.tick,1);
 const csv=await (await request('/api/export?id='+id+'&stock=A&timeframe=1')).text();assert.ok(csv.includes('open,high,low,close,volume,turnover,trades,vwap,complete'));assert.equal(csv.trim().split('\n').length,3);const history=await (await request('/api/history?id='+id+'&count=0')).json();assert.equal(history.length,2);assert.ok(history.at(-1).complete);assert.ok(!JSON.stringify(history).includes('fair'));
 const ledger=await (await request('/api/query?id='+id,{method:'get_ledger',args:{count:0}})).json();assert.ok(ledger.some(r=>r.type==='borrow'));assert.ok(ledger.some(r=>r.type==='income'));assert.ok(ledger.some(r=>r.type==='loan_interest'));
 const own=await (await request('/api/query?id='+id,{method:'get_player'})).json();assert.equal(own.positions.length,5);assert.equal(own.cost.length,5);
 const publicState=await (await request('/api/query?id='+id,{method:'get_snapshot'})).json();assert.equal(publicState.traders.length,51);assert.ok(!Object.hasOwn(publicState.traders[0],'valuationBias'));assert.ok(!Object.hasOwn(publicState.stocks[0],'fair'));
 console.log('HTTP: configuration, SDK, borrowing, process control, round lock, CSV, complete personal ledger and public snapshot passed.');}
main().catch(e=>{console.error(e);process.exitCode=1;});
