'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {Market}=require('./engine-v2.cjs'),{GameSession}=require('./controller.cjs');
const close=(a,b,eps=1e-5)=>assert.ok(Math.abs(a-b)<eps,`${a} != ${b}`);
const shares=m=>m.stocks.map((_,i)=>m.people.reduce((s,a)=>s+a.shares[i],0));
function invariant(m,initialShares){
 close(m.people.reduce((s,a)=>s+a.cash,0)+m.bankCash,m.initialCash+m.minted,.001);
 assert.deepEqual(shares(m),initialShares);
 for(const a of m.people){assert.ok(a.cash>=-1e-6);assert.ok(m.reservedCash(a.id)<=a.cash+1e-6);a.shares.forEach((q,i)=>{assert.ok(q>=0);assert.ok(m.reservedShares(a.id,i)<=q);});}
 for(const s of m.stocks){for(const b of s.candles){assert.ok(b.high>=Math.max(b.open,b.close));assert.ok(b.low<=Math.min(b.open,b.close));if(b.volume)close(b.vwap,b.turnover/b.volume);}}
}
async function main(){
 for(const count of [50,123,1000,5000]){const m=new Market({count,seed:42});assert.equal(m.agents.length,count);assert.equal(m.playerId,count);for(const a of m.agents)assert.ok(a.type===5?a.knownSymbols.length>=1&&a.knownSymbols.length<=3:a.knownSymbols.length===0);const total=shares(m);m.step();invariant(m,total);const speeds=m.actionSequence.filter(a=>a.phase==='speed'),others=m.actionSequence.filter(a=>a.phase==='normal');assert.equal(speeds.length,Math.max(1,Math.floor(count*.02)));assert.equal(speeds.length+others.length,count+speeds.length);for(const a of m.speedAgents)assert.equal(m.actionSequence.filter(x=>x.id===a.id).length,2);assert.ok(m.actionSequence.slice(0,speeds.length).every(a=>m.people[a.id].type===6));assert.ok(!JSON.stringify(m.snapshot()).includes('"fair"'));assert.ok(!JSON.stringify(m.snapshot()).includes('fairHistory'));}
 assert.throws(()=>new Market({count:49}));assert.throws(()=>new Market({count:123.5}));
 const fifo=new Market({count:50,seed:7});fifo.orders=[];fifo.people[0].shares[0]=10;fifo.people[1].shares[0]=10;fifo.people[2].cash=10000;fifo.place(0,0,'sell',2,100,30);fifo.place(1,0,'sell',2,100,30);fifo.place(2,0,'buy',3,110,30);assert.equal(fifo.trades[0].seller,1);assert.equal(fifo.trades[1].seller,0);assert.equal(fifo.stocks[0].price,100);assert.equal(fifo.orders.find(o=>o.owner===1).qty,1);const historical=JSON.stringify(fifo.stocks[0].candles[0]);fifo.submit(0,'buy',1,'market');assert.equal(JSON.stringify(fifo.stocks[0].candles[0]),historical);assert.equal(fifo.stocks[0].pendingBar.volume,4);fifo.step();assert.ok(fifo.stocks[0].candles[1].volume>=4);
 const margin=new Market({count:50,seed:9});margin.orders=[];const p=margin.player;p.cash=0;p.debt=8000;p.shares=[100,0,0,0,0];margin.stocks[0].price=100;margin.people[0].cash=20000;margin.place(0,0,'buy',100,100,30);margin.checkMargin();assert.equal(p.shares[0],57);assert.equal(p.debt,3700);assert.ok(margin.margin().ratio>=.35);assert.equal(p.liquidating,false);assert.ok(p.debt>0&&p.shares[0]>0);
 const noBid=new Market({count:50,seed:9});noBid.orders=[];noBid.player.cash=0;noBid.player.debt=8000;noBid.player.shares=[100,0,0,0,0];noBid.checkMargin();assert.ok(noBid.player.liquidating);assert.equal(noBid.player.debt,8000);assert.equal(noBid.submit(0,'buy',1,'market').ok,false);noBid.people[0].cash=20000;noBid.place(0,0,'buy',100,100,30);noBid.checkMargin();assert.equal(noBid.player.liquidating,false);
 const trends=[];for(const seed of [17,42,123]){const m=new Market({count:1000,seed}),initialShares=shares(m);m.setLeverage(3);m.borrow(1000);for(let t=0;t<260;t++){if(t===2)m.submit(0,'buy',5,'market');if(t===4)m.repay(200);m.step();}invariant(m,initialShares);assert.equal(m.candles(0,1,0).length,261);assert.equal(m.snapshot().stocks[0].candles.length,240);const aggregate=m.candles(0,5,0);assert.equal(aggregate.reduce((s,b)=>s+b.volume,0),m.candles(0,1,0).reduce((s,b)=>s+b.volume,0));trends.push({seed,prices:m.stocks.map(s=>s.price)});}
 console.log('Engine: conservation, FIFO, immutable candles, full archive, phases and selective liquidation passed.',JSON.stringify(trends));
 const session=new GameSession('verification-v2',{count:123,seed:42});const code=`#include "market.hpp"\n#include <expected>\n#include <thread>\n#include <chrono>\nint main(){static int local=0;market::log("fresh="+std::to_string(++local));auto a=market::account();auto s=market::stock("A");auto b=market::book("A");auto h=market::history("A",0);if(market::phase()!="player-bot"||h.empty()||s.price<=0)return 2;int n=market::memory_get("rounds").integer();market::memory_set("rounds",n+1);market::memory_set("中文",market::Json::parse("\\\"\\\\u4f60\\\\u597d\\\\ud83d\\\\ude00\\\""));if(n==0){if(!market::set_leverage(100).ok||!market::borrow(100).ok)return 3;auto r=market::buy("A",1);if(!r.ok)return 4;auto o=market::limit_buy("B",1,1,10);if(!o.ok||!market::cancel_order(o.order_id).ok)return 5;if(!market::repay(100).ok)return 6;}auto orders=market::orders();auto ranks=market::rankings("trading");std::this_thread::sleep_for(std::chrono::milliseconds(100));return 0;}`;
 await session.bot.compile({source:code,name:'verify.cpp'});session.bot.enabled=true;const advancing=session.step();assert.ok(session.busy);assert.ok(session.market.inTick);assert.equal(session.market.stocks[0].candles.at(-1).complete,false);const one=await advancing;assert.equal(one.run.code,0,one.run.output);assert.equal(session.busy,false);assert.equal(one.state.tick,1);assert.ok(one.run.calls>=10);assert.ok(one.run.output.includes('fresh=1'));assert.equal(session.memory.get('中文'),'你好😀');const two=await session.step();assert.equal(two.run.code,0);assert.ok(two.run.output.includes('fresh=1'));assert.equal(session.memory.get('rounds'),2);assert.ok(session.market.player.shares[0]>=1);assert.equal(session.market.player.debt,0);await session.step(false);assert.equal(session.memory.get('rounds'),2);assert.ok(session.bot.enabled);session.bot.enabled=false;await session.step();assert.equal(session.memory.get('rounds'),2);
 await session.bot.compile({source:'#include <thread>\n#include <chrono>\nint main(){std::this_thread::sleep_for(std::chrono::seconds(30));}',name:'hang.cpp'});session.bot.enabled=true;session.bot.timeout=1;let row=await session.step();assert.ok(row.run.error.includes('超过'));assert.equal(session.busy,false);assert.equal(session.bot.enabled,false);session.bot.enabled=true;session.bot.timeout=10;const stopped=session.step();setTimeout(()=>session.bot.stop(),100);row=await stopped;assert.ok(row.run.error);assert.equal(session.busy,false);assert.equal(session.market.inTick,false);assert.equal(session.bot.enabled,false);
 await assert.rejects(()=>session.bot.compile({source:'invalid c++ source',name:'invalid.cpp'}));assert.equal(session.bot.executable,null);assert.equal(session.bot.compiling,false);assert.equal(session.bot.enabled,false);
 session.bot.history=Array.from({length:40},(_,i)=>({tick:40-i}));assert.equal(session.bot.status().history[0].tick,40);console.log('C++23: fresh processes, persistent Unicode memory, trading/leverage APIs, skip, disable, timeout, stop and compilation failures passed.');
}
main().catch(e=>{console.error(e);process.exitCode=1;});
