'use strict';
const fs=require('node:fs'),path=require('node:path'),{Market}=require('../engine-v2.cjs');
const seeds=[7,17,42,91,123,314,20261005,20261006];
function invest(m,leverage){const p=m.player,eq=m.equity(p);if(p.liquidating||eq<=0)return;const target=eq*leverage,held=p.shares.reduce((v,q,i)=>v+q*m.stocks[i].price,0),missing=Math.max(0,target-held);m.setLeverage(leverage);const needed=Math.min(m.margin().capacity,Math.max(0,missing-m.availableCash(p.id)));if(needed>=.01)m.borrow(Math.floor(needed*100)/100);
 for(let i=0;i<5;i++){let budget=Math.min(m.availableCash(p.id),Math.max(0,target/5-p.shares[i]*m.stocks[i].price)),qty=0;for(const o of m.orderIndex.iterate(i,'sell')){if(o.owner===p.id)continue;const n=Math.min(o.qty,Math.floor((budget+1e-8)/o.price));qty+=n;budget-=n*o.price;if(n<o.qty)break;}if(qty)m.trade(p.id,i,'buy',qty);}
 if(p.debt&&m.availableCash(p.id)>=.01)m.repay(m.availableCash(p.id));
}
function simulate(seed,ticks=360,leverage=0,options={}){const m=new Market({count:1000,seed,...options}),initialShares=m.stocks.map((_,i)=>m.agents.reduce((sum,a)=>sum+a.shares[i],0));let high=1,drawdown=0,up=0,down=0,liquidated=false,peakLeverage=1;const checkpoints=[];
 for(let t=1;t<=ticks;t++){m.beginTick();if(leverage&&t%6===1)invest(m,leverage);m.finishTick();const index=m.stocks.reduce((v,s)=>v+s.price/s.start,0)/5;high=Math.max(high,index);drawdown=Math.max(drawdown,1-index/high);const delta=m.stocks.reduce((v,s)=>v+Math.log(s.price/s.previous),0)/5;if(delta>1e-9)up++;if(delta<-1e-9)down++;liquidated||=m.player.liquidating;peakLeverage=Math.max(peakLeverage,m.margin().leverage||1);if(t%90===0)checkpoints.push({tick:t,indexReturnPct:(index-1)*100});}
 const index=m.stocks.reduce((v,s)=>v+s.price/s.start,0)/5,analysts=m.agents.filter(a=>a.type===7),variants={};for(const a of analysts){const key=a.analystStyle||'legacy';variants[key]??={count:0,debt:0,investment:0};variants[key].count++;variants[key].debt+=a.debt;variants[key].investment+=m.investment(a);}
 return {seed,ticks,leverage,returns:m.stocks.map(s=>(s.price/s.start-1)*100),indexReturnPct:(index-1)*100,maximumIndexDrawdownPct:drawdown*100,upTicks:up,downTicks:down,checkpoints,minted:m.minted,initialShares,player:{equity:m.equity(m.player),investment:m.investment(m.player),debt:m.player.debt,peakLeverage,liquidating:liquidated,completedGoal:!!m.won},analystVariants:variants};
}
function summarize(rows){return {cases:rows.length,meanIndexReturnPct:rows.reduce((s,r)=>s+r.indexReturnPct,0)/rows.length,allFiveUpCases:rows.filter(r=>r.returns.every(v=>v>0)).length,negativeStockCases:rows.reduce((s,r)=>s+r.returns.filter(v=>v<0).length,0),meanDrawdownPct:rows.reduce((s,r)=>s+r.maximumIndexDrawdownPct,0)/rows.length,playerLossCases:rows.filter(r=>r.player.investment<0).length,liquidatingCases:rows.filter(r=>r.player.liquidating).length};}
if(require.main===module){const target=process.argv[2]||path.join(__dirname,'../runtime/balance-current.json'),rows=seeds.map(seed=>simulate(seed));const strategies=[10,100].flatMap(leverage=>seeds.slice(0,4).map(seed=>simulate(seed,360,leverage)));const report={date:new Date().toISOString(),count:1000,ticks:360,seeds,summary:summarize(rows),markets:rows,strategies,strategySummary:Object.fromEntries([10,100].map(l=>[l,summarize(strategies.filter(r=>r.leverage===l))]))};fs.mkdirSync(path.dirname(path.resolve(target)),{recursive:true});fs.writeFileSync(target,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({target,summary:report.summary,strategySummary:report.strategySummary}));}
module.exports={simulate,summarize,invest};
